### ISSUE TITLE
how to install deepspeed in window10?

### ISSUE THREAD

**Issue by Zhoushunchaomacau** [KimMeen/Time-LLM#105]
When i want to install deepspeed in window 10, i meet this problem.
![屏幕截图 2024-06-04 144523](https://github.com/KimMeen/Time-LLM/assets/169748521/80525b74-c591-4f75-90e9-e41feca975a2)

**Comment by lilianedng** [comment]
Greetings, I am also a Window 10 user and during the process of installing the dependencies, I also encountered a plethora of issues, one of which resembled the one you are having right now. My suggestion after debugging, going through all of the discussion thread, is to install and set up WSL which comes with Ubuntu running on your local machine, make sure you use venv or conda  to avoid any entrypoint command. Hope this helps you

**Comment by Zhoushunchaomacau** [comment]
After I fixed that problem, 'run_main' reported an error on line 167. Jump to the subprocess, reported this error, may I ask you have encountered?
![sub](https://github.com/KimMeen/Time-LLM/assets/169748521/197c8366-2a97-4b4e-a901-dcd2aef250ce)


> Greetings, I am also a Window 10 user and during the process of installing the dependencies, I also encountered a plethora of issues, one of which resembled the one you are having right now. My suggestion after debugging, going through all of the discussion thread, is to install and set up WSL which comes with Ubuntu running on your local machine, make sure you use venv or conda to avoid any entrypoint command. Hope this helps you

**Comment by zhengyu-su** [comment]
你好，请问一下你是怎么解决的在windows上运行的问题呢？我现在解决了deepspeed的安装，但是还有很多其他的报错比如说nccl的问题，想问一下你是怎么处理的哇
