### ISSUE TITLE
Can it support other llm?

### ISSUE THREAD

**Issue by YinzhenWang** [KimMeen/Time-LLM#107]
Thank you for bring such wonderful work.
I have not read the code carefully now and I just want to know could it support other latest llm like llama3 or qwen2 for better performance? ( like just modify the code at from_pretrained)

**Comment by zhangmaosen** [comment]
I have modify llm to qwen2, it can work

**Comment by kwuking** [comment]
> I have modify llm to qwen2, it can work

Thanks for your support and reply.
