### ISSUE TITLE
My friend, why delete the final checkpoint after train?

### ISSUE THREAD

**Issue by zhangmaosen** [KimMeen/Time-LLM#108]
https://github.com/KimMeen/Time-LLM/blob/d3f29569e314af6eeaf6920b368076529e9c98c8/run_main.py#L269C1-L269C47
Thank you for your reply

**Comment by kwuking** [comment]
Thank you for your attention to our work. This was purely done considering the resources, to avoid running out of disk space. If you need more storage, you can comment out that code.
