### ISSUE TITLE
Scripts for Weather, ECL and Traffic

### ISSUE THREAD

**Issue by assdwd** [KimMeen/Time-LLM#11]
Only scripts for ETT and M4 were provided. Could you please provide the relevant scripts for Weather, ECL, and Traffic mentioned in the paper?

**Comment by bruciebruce** [comment]
Unzip **time-series-dataset.zip** provided in the dataset directory.

**Comment by assdwd** [comment]
No, you misunderstand. I meant scripts to reproduce the data from the paper, not the datasets themselves. Similar to https://github.com/KimMeen/Time-LLM/blob/main/scripts/TimeLLM_ETTh1.sh, which provides parameters for reproducing ETTh1, but does not provide scripts to reproduce the results of ECL, Weather, and Traffic from the paper.

**Comment by bruciebruce** [comment]
Oh, okay.  Thanks.

**Comment by KimMeen** [comment]
@assdwd Thank you for the feedback👍 We have added addtional demo scripts. See https://github.com/KimMeen/Time-LLM/tree/main/scripts
