### ISSUE TITLE
Clarification on Unused Parameters in TimeLLM Forecast Function

### ISSUE THREAD

**Issue by Ma-Chenbin** [KimMeen/Time-LLM#116]
Hi Team,

Thanks for your great work! I'm currently working with the TimeLLM model as described in your ICLR paper, "Time-LLM: Forecasting and Understanding Time Series with Pretrained Language Models."

Upon reviewing the paper and the associated implementation, I noticed that the parameters `x_mark_enc`, `x_dec`, and `x_mark_dec` are passed to the `forward` method but do not appear to be utilized in the `forecast` function. Specifically, these parameters are passed through the method signatures but are not referenced within the function body for any operations or computations.

Here's the relevant code snippet in `./Time-LLM/models/TimeLLM`:

```python
def forward(self, x_enc, x_mark_enc, x_dec, x_mark_dec, mask=None):
    if self.task_name == 'long_term_forecast' or self.task_name == 'short_term_forecast':
        dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
        return dec_out[:, -self.pred_len:, :]
    return None

def forecast(self, x_enc, x_mark_enc, x_dec, x_mark_dec):
    # ... various operations on x_enc ...
    return dec_out
```

Is this the intended behavior, or are these parameters supposed to be used in a specific way that I'm missing?

Thank you for your time and consideration. I look forward to your guidance on this matter.

**Comment by kwuking** [comment]
Thank you very much for your interest in our work. Your understanding is correct. Currently, the variables x_mark_enc, x_dec, and x_mark_dec are not involved in the actual training process. We are using the [Time-Series-Library](https://github.com/thuml/Time-Series-Library) framework for reference, and to maintain consistency, we have kept these parameters.
