### ISSUE TITLE
Item representations in M/MS task

### ISSUE THREAD

**Issue by jexterliangsufe** [KimMeen/Time-LLM#117]
Great works. 
When I dive into data processing codes for Traffic or Electricity datasets, I find that `seq_x` length is (seq_len, ), which means multi variates are split to univariate and considered by model seperately. 
Then I noticed that the model actually accept (B, T, C) input where C=1, which means the model doesn't know which variate is feeded into. 
The question is, have you considered about extracting the item representation and feeding them into a new embedding layer like `static embedding layer`?

**Comment by kwuking** [comment]
Thank you very much for your interest in our work. Your understanding is correct. Currently, Time-LLM adopts a channel-independent approach and does not consider the interactions between multivariate variables. The use of a static embedding layer you mentioned is indeed a very interesting method. We have also explored this approach. However, there is a small issue that we have not yet been able to solve adequately: how to handle unseen time series during inference, as new time series are not included in the original static encoding. This is something that may require further thought.

**Comment by kwuking** [comment]
> Thanks for your reply. In my application scenario, there is no unseen time series during inference. Interestingly, mae from TimeLLM is lower than the one from TemporalFusionTransformer which is fed into multi features and using static embedding layer. So the necessity of item representations should be re-considered.

TimeLLM is based on llama 7b as the base model. If the dataset is relatively small, training can be challenging and may not be suitable for a large model. If you find a reasonable solution to address your issue, that would be great.
