### ISSUE TITLE
请问是否出现过训练时验证集的loss和训练和测试集的loss差异较大的情况？

### ISSUE THREAD

**Issue by zsczszsc** [KimMeen/Time-LLM#119]
如图，这是某一次训练的情况，其他的情况与这个类似，loss函数为mse
Train Loss: 0.3769871 Vali Loss: 0.7908717 Test Loss: 0.3968912 MAE Loss: 0.4176204
非常感谢您的工作！

**Comment by kwuking** [comment]
感谢您对于我们工作的关注，目前valid loss用于early stop策略使用，并不参与实际的训练工程，您可以尝试调整模型参数再进行下尝试。

**Comment by my-source10** [comment]
> 如图，这是某一次训练的情况，其他情况与这个类似，loss函数为mse 列车损失：0.3769871 Vali 损失：0.7908717 测试损失：0.3968912 MAE 损失：0.4176204 非常感谢您的工作！

我也出现了这个问题，请问你解决了吗
