### ISSUE TITLE
Undefined arguments for the forecast function

### ISSUE THREAD

**Issue by marcopeix** [KimMeen/Time-LLM#12]
In the forecast method in TimeLLM, there are arguments that are not defined anywhere

` def forecast(self, x_enc, x_mark_enc, x_dec, x_mark_dec):`

What do these parameters refer to? They are not defined in the model class or in the bash scripts to run the model

**Comment by KimMeen** [comment]
We follow the general pipeline in [Time-Series-Library](https://github.com/thuml/Time-Series-Library), but note that  `x_mark_enc ` and `x_mark_dec ` are not used in our model.

Here is an example of how `x_mark` involved:

https://github.com/thuml/Time-Series-Library/blob/8782a590950b4ee31a0d2d66fc30b761689c3636/models/TimesNet.py#L112

We have not used such temporal featrues.
