### ISSUE TITLE
Question about "dec_out"

### ISSUE THREAD

**Issue by tokaka22** [KimMeen/Time-LLM#120]
```python
dec_out = self.output_projection(dec_out[:, :, :, -self.patch_nums:])
dec_out = dec_out.permute(0, 2, 1).contiguous()
```

Why just cut "-self.patch_nums:" in the last dimension of dec_out?
Thanks for your attention!

**Comment by kwuking** [comment]
Thank you for your attention to our work. You can refer to this issue #59

**Comment by tokaka22** [comment]
Thank you for your reply!
I was more focused on model robustness before, so I may not be familiar with time series prediction.
1. Why is it that under the setting of `--features M`, when reading data, the index selects data from this length, that is, it is possible to read HUFL data to predict HUFL data, and it is also possible to read OT data to predict OT data?
```python
    def __len__(self):
        return (len(self.data_x) - self.seq_len - self.pred_len + 1) * self.enc_in
```
2. In addition, I think that in `M` ​​mode, for ETTh1, the input should be 7-dimensional features, and the output should also be 7-dimensional features; in `MS` mode, for ETTh1, the input should be 7-dimensional features, and the output should be OT (single dimension). Is this understanding correct?
