### ISSUE TITLE
推理脚本

### ISSUE THREAD

**Issue by leoneyar** [KimMeen/Time-LLM#121]
您好，请问能把推理脚本分享一下吗，非常感谢

**Comment by leecmy08** [comment]
你好，请问一下 我已经得到了checkpoint文件，如何进行模型加载

**Comment by leoneyar** [comment]
model.load_state_dict(torch.load("路径"))，我现在能通过这个加载，不过在推理方面还出现问题

**Comment by leecmy08** [comment]
还麻烦您指导一下具体步骤，或者是否能分享代码，我目前得到checkpoint压缩包，先进行解压操作吗，然后您指的路径是什么文件的路径？
