### ISSUE TITLE
checkpoint解析

### ISSUE THREAD

**Issue by leecmy08** [KimMeen/Time-LLM#122]
您好，打扰您了，我想尝试复现您的代码，目前已经生成了checkpoint压缩包，如何解析该压缩包，请问是否有对应代码？

**Comment by kwuking** [comment]
你好，感谢对于我们工作的关注，checkpoint压缩包是指训练完TimeLLM之后的权重文件嘛，如果您处理后是tar包可以直接解压，参考exp文件中的text方法的代码加载模型权重即可。

**Comment by leecmy08** [comment]
checkpoint压缩包是指训练完TimeLLM之后的权重文件，我是希望看到代码跑的最终的结果，包括MAE,MSE这些指标等，不知道您是否可以提供指导，目前我仅有一个checkpoint压缩包，我希望看到实验的结果，感谢您了

**Comment by leecmy08** [comment]
请问模型的预测结果 也是在checkpoint文件里面吗

**Comment by leecmy08** [comment]
作者  还有一个问题问您，我现在加载模型后，做推理后的ETTH1数据集预测和真实值是其中的某一列，并不是最后的OT油温，不知道这个问题应该如何解决，模型是一个多输入多输出的模型吗？

**Comment by lphhh123** [comment]
Hello, sorry to bother you. I have been reproducing my paper recently. How did I obtain the compressed checkpoint file? After configuring the environment, running the. sh file will result in error. Do you need to debug and modify in the reverse direction? Thank you very much.

**Comment by lphhh123** [comment]
Hello, sorry to bother you. I have been reproducing this paper recently. How did I obtain the compressed checkpoint file? After configuring the environment, running the. sh file will result in an error. Do you need to debug and modify in the reverse direction? Thank you very much

**Comment by lphhh123** [comment]
Hello, sorry to bother you. I have been reproducing this paper recently. How did I obtain the compressed checkpoint file? After configuring the environment, running the '. sh' file will result in an error， and running run_ma4.py will also result in an error. Do I need to debug and modify in the reverse direction? Thank you very much
![image](https://github.com/user-attachments/assets/d42d68ae-6721-4b48-a362-b3c1d61178cc)

**Comment by kwuking** [comment]
> 作者 还有一个问题问您，我现在加载模型后，做推理后的ETTH1数据集预测和真实值是其中的某一列，并不是最后的OT油温，不知道这个问题应该如何解决，模型是一个多输入多输出的模型吗？

感谢对于我们工作的关注，目前我们使用了channel independent策略（这个是从PatchTST开始被广泛采用的），目前是将多元时序转换成了一元时序来进行处理的，因此并不会只输出最后的OT列的预测结果。

**Comment by kwuking** [comment]
> Hello, sorry to bother you. I have been reproducing this paper recently. How did I obtain the compressed checkpoint file? After configuring the environment, running the '. sh' file will result in an error， and running run_ma4.py will also result in an error. Do I need to debug and modify in the reverse direction? Thank you very much

Thanks for your attention. Currently, I am running the script without any issues. Could you please provide more logs to help with the analysis? Also, since we are using LLM as the base model and employing complex frameworks like DeepSpeed, you might need to check the related configurations and environment to ensure there are no problems.

**Comment by ShuoHH** [comment]
>您好，请问您关于TimeLLM加载权重的问题解决了吗，能否follow一下您的工作，如果可以将
不胜感激

**Comment by ShuoHH** [comment]
> 你好，感谢对于我们工作的关注，checkpoint压缩包是指训练完TimeLLM之后的权重文件嘛，如果您处理后是tar包可以直接解压，参考exp文件中的text方法的代码加载模型权重即可。

您好，我保存的文件是zip压缩包，请问您指的exp文件中的text方法是？，因为我在源码中并未找到exp文件以及text方法

**Comment by ShuoHH** [comment]
> 你好，感谢对于我们工作的关注，checkpoint压缩包是指训练完TimeLLM之后的权重文件嘛，如果您处理后是tar包可以直接解压，参考exp文件中的text方法的代码加载模型权重即可。

您好，我保存的权重文件是zip压缩包，请问您指的exp文件中的text方法是？，因为我在源码中并未找到exp文件以及text方法？ 对此我应该如何使得模型加载权重？ 希望收到您的回答，将不胜感激，祝生活顺利
