### ISSUE TITLE
About time stamps

### ISSUE THREAD

**Issue by ShaoqLin** [KimMeen/Time-LLM#123]
Hi,
Thank you for your excellent work on Time-LLM, which has been very inspiring. I am new to time series analysis and have some questions regarding a recurring observation in other issues: "x_mark_enc, x_dec, x_mark_dec is not used in training."
From my understanding, x_mark_enc and x_mark_dec contain timestamps as indicated in Dataset_ETT_hour.py lines 99-100. However, in your experiments, these timestamps are ignored. I suspect this omission is due to the use of "relative timestamps," where only the time within the input sequence (e.g., seq_len=512) is utilized, rather than the entire dataset with "absolute timestamps." My questions are as follows:
1. If I understand correctly, what is the difference between using "relative timestamps" and "absolute timestamps"?
2. In cases where the dataset is very large, would "absolute timestamps" be beneficial?

Best regards

**Comment by kwuking** [comment]
> Hi, Thank you for your excellent work on Time-LLM, which has been very inspiring. I am new to time series analysis and have some questions regarding a recurring observation in other issues: "x_mark_enc, x_dec, x_mark_dec is not used in training." From my understanding, x_mark_enc and x_mark_dec contain timestamps as indicated in Dataset_ETT_hour.py lines 99-100. However, in your experiments, these timestamps are ignored. I suspect this omission is due to the use of "relative timestamps," where only the time within the input sequence (e.g., seq_len=512) is utilized, rather than the entire dataset with "absolute timestamps." My questions are as follows:
> 
> 1. If I understand correctly, what is the difference between using "relative timestamps" and "absolute timestamps"?
> 2. In cases where the dataset is very large, would "absolute timestamps" be beneficial?
> 
> Best regards

Thank you for your attention to our work. We are currently focusing on Time-LLM and utilizing features like timestamps. Based on my experience with other models (such as iTransformer, TimeMixe, and TimesNetr), using these features should be beneficial. You can certainly try them out. Using absolute timestamps may potentially enhance the model's performance, but I haven't conducted any related experiments yet, so I can't make an accurate judgment.
