### ISSUE TITLE
Question regarding the dataset's StandardScaler()

### ISSUE THREAD

**Issue by khchul** [KimMeen/Time-LLM#124]
Thank you for your great work!
I've been looking through your paper and the implementation, but I have a question regarding the scaling.
In the paper, it is said that "Each input channel X(i) is first individually normalized to have zero mean and unit standard deviation". I understood that this is done in the TimeLLM's normalize_layers.
However, the data itself has already been scaled through data_loader.py and as far as I know, inverse_transform() doesn't seem to appear elsewhere.
Shouldn't the scale variable in the data_loader be set to False?

**Comment by kwuking** [comment]
> Thank you for your great work! I've been looking through your paper and the implementation, but I have a question regarding the scaling. In the paper, it is said that "Each input channel X(i) is first individually normalized to have zero mean and unit standard deviation". I understood that this is done in the TimeLLM's normalize_layers. However, the data itself has already been scaled through data_loader.py and as far as I know, inverse_transform() doesn't seem to appear elsewhere. Shouldn't the scale variable in the data_loader be set to False?

Thank you for your attention. We are currently using the framework template in TSLib. At present, the comparisons for these well-acknowledged benchmarks are all conducted after normalization. You can refer to [TSLib](https://github.com/thuml/Time-Series-Library) for more information.
