### ISSUE TITLE
Question about fine-tuning

### ISSUE THREAD

**Issue by NickDatLe** [KimMeen/Time-LLM#15]
When I run the command:

`bash ./scripts/TimeLLM_ETTh1.sh `

Am I training the 7b_hf model to translate time series data to a format that is suitable for an LLM to do time series forecasting?

Would I then take the trained model to translate new time series data and use that translated data to feed into an LLM to make predictions?

**Comment by KimMeen** [comment]
Hi @NickDatLe 

> Am I training the 7b_hf model to translate time series data to a format that is suitable for an LLM to do time series forecasting?

Yes. This adapts a frozen Llama-7b model to diagest the time series inputs and forecast accordingly.

> Would I then take the trained model to translate new time series data and use that translated data to feed into an LLM to make predictions?

Yes. See this example: https://github.com/KimMeen/Time-LLM/blob/main/run_pretrain.py and https://github.com/KimMeen/Time-LLM/blob/main/scripts/TimeLLM_ETTh1_ETTh2.sh
