### ISSUE TITLE
Error in running example script

### ISSUE THREAD

**Issue by XJTLUmedia** [KimMeen/Time-LLM#16]
RuntimeError: CUDA error: invalid device ordinal
OSError: Incorrect path_or_model_id: '/mnt/alps/modelhub/pretrained_model/LLaMA/7B_hf/'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

I just use git clone to my local computer, I can find my GPU on using Nvidia-SMI command, however, when I run the first example script,

`bash ./scripts/TimeLLM_ETTh1.sh `

 I found this error, does this mean I have to download LLaMa to use or there are some modifications I need to do with bash script?

**Comment by NickDatLe** [comment]
For the ordinal issue, if you have just 1 GPU, then remove the --multi_gpu flag from your bash script (ie TimeLLM_ETHTh1.sh). 

For the incorrect path issue, comment out the "/mnt..." paths and uncomment out the HuggingFace model path in the file: models/TimeLLM.py

https://github.com/KimMeen/Time-LLM/blob/main/models/TimeLLM.py
