### ISSUE TITLE
llama-7b command correct? 

### ISSUE THREAD

**Issue by Naman-Choudhary-AI-ML** [KimMeen/Time-LLM#18]
OSError: huggyllama/llama-7b does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 715682 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 715683) of binary:

Facing this error. Is the llama-7b command accurate? Can someone help me figure this out. 

Thanks.

**Comment by Naman-Choudhary-AI-ML** [comment]
Downloaded the model. This is fixed.

**Comment by guoqian-01** [comment]
I'm experiencing the same problem, may I ask how you solved it?
