### ISSUE TITLE
Running Time-LLM on GPT2

### ISSUE THREAD

**Issue by NimeeshaChan** [KimMeen/Time-LLM#23]
Hello, would it be possible to share the scripts (e.g. for TimeLLM.py, modeling_utils.py, etc.) adapted for GPT2 please? I do not have enough compute power to train on LLaMA in a feasible amount of time. I have attempted to adapt it on my own but am running into a lot of errors. Thank you very much!

**Comment by lizhuoq** [comment]
Comment out the llama and replace it with the following code, which is useful for me and hopefully helpful for you.
```
from transformers import GPT2Tokenizer, GPT2Model, GPT2Config

self.gpt2_config = GPT2Config.from_pretrained(
    gpt2_root, 
    output_attentions=True, 
    output_hidden_states=True
)
self.gpt2 = GPT2Model.from_pretrained(gpt2_root, config=self.gpt2_config)
self.tokenizer = GPT2Tokenizer.from_pretrained(gpt2_root)
```
And make corresponding modifications to the following places.

**Comment by KimMeen** [comment]
Thank you, @lizhuoq 😄. I hope this solved your quesiton, @NimeeshaChan. Please re-open this issue if there are other questions.
