### ISSUE TITLE
Model save path

### ISSUE THREAD

**Issue by NickDatLe** [KimMeen/Time-LLM#24]
I trained the model for 10 epochs and I didn't see any weights saved any where, but I did see this:

```
if accelerator.is_local_main_process:
    path = './checkpoints'  # unique checkpoint saving path
    del_files(path)  # delete checkpoint files
    accelerator.print('success delete checkpoints')
```

were the checkpoints deleted after training? If so, where are the best weights?

**Comment by KimMeen** [comment]
@NickDatLe Good catch! Please disable this part if you wish to keep model checkpoints. We implemented this to free up disk space during our experiments with Time-LLM.
