### ISSUE TITLE
Clarification on Dataset-Specific Prompt Utilization

### ISSUE THREAD

**Issue by zqiao11** [KimMeen/Time-LLM#27]
Hi authors,

I've been exploring the TimeLLM model and have some questions regarding its implementation of prompts for various datasets.

I observed in the repository that there is a collection of data-specific text descriptions within `dataset/prompt_bank`. However, it seems the TimeLLM model doesn't leverage these descriptions automatically. For instance, the implementation appears to consistently utilize the prompt for the ETT dataset by default, as seen in the model's code [here](https://github.com/KimMeen/Time-LLM/blob/main/models/TimeLLM.py#L142).

Additionally, while the dataset-specific prompt is passed as the `content` argument in the main function ([example here](https://github.com/KimMeen/Time-LLM/blob/main/run_main.py#L136)), it does not appear to be used in the subsequent training or testing process.

Could you please provide guidance on whether the prompts in `models/TimeLLM` require manual updates for each dataset, or if there is an intended mechanism based on the `content` argument that should automatically handle this?

Thank you for your assistance.

**Comment by kwuking** [comment]
Hi, we have updated the code to refine this section. You can use the latest model code. 

> Hi authors,
> 
> I've been exploring the TimeLLM model and have some questions regarding its implementation of prompts for various datasets.
> 
> I observed in the repository that there is a collection of data-specific text descriptions within `dataset/prompt_bank`. However, it seems the TimeLLM model doesn't leverage these descriptions automatically. For instance, the implementation appears to consistently utilize the prompt for the ETT dataset by default, as seen in the model's code [here](https://github.com/KimMeen/Time-LLM/blob/main/models/TimeLLM.py#L142).
> 
> Additionally, while the dataset-specific prompt is passed as the `content` argument in the main function ([example here](https://github.com/KimMeen/Time-LLM/blob/main/run_main.py#L136)), it does not appear to be used in the subsequent training or testing process.
> 
> Could you please provide guidance on whether the prompts in `models/TimeLLM` require manual updates for each dataset, or if there is an intended mechanism based on the `content` argument that should automatically handle this?
> 
> Thank you for your assistance.

Hi, we have updated the code to enhance this part. You can use the latest model code. If you want to use a specific prompt for each dataset, you need to enable the prompt_domain setting in the configuration.
