### ISSUE TITLE
compute envrionment on high variable time-series

### ISSUE THREAD

**Issue by raycai420** [KimMeen/Time-LLM#30]
Hi here,

Thank you for sharing the good work! We are trying to run your model on multivariate timeseries with high number of channels (traffic, ECL, and weather). We found it really hard to fit on our compute envrionment (4 x 48GA6000) even with batch size of 1. 

Could you share a rough estimate of compute environment needed to run above datasets? 

Thank you so much!

**Comment by kwuking** [comment]
> Hi here,
> 
> Thank you for sharing the good work! We are trying to run your model on multivariate timeseries with high number of channels (traffic, ECL, and weather). We found it really hard to fit on our compute envrionment (4 x 48GA6000) even with batch size of 1.
> 
> Could you share a rough estimate of compute environment needed to run above datasets?
> 
> Thank you so much!

Hi, in data_loader.py, we have processed the datasets for traffic, ECL, and weather with channel independent handling, making them easily loadable for training and prediction. You can refer to our scripts to give it a try.
