### ISSUE TITLE
Custom data utilization

### ISSUE THREAD

**Issue by hxuaj** [KimMeen/Time-LLM#32]
Hi,

Thanks for the great work.

I was wondering if there is any requirements or suggestions on utilizing Time-LLM on custom data. If I want to fit the model to new data, what parts of the code shall I take into consideration in both training and testing time?

**Comment by kwuking** [comment]
Hi, if you want to run your datasets, you can modify the data_factory.py and data_loader.py files, and add the corresponding data processing code accordingly
