### ISSUE TITLE
Replication set up

### ISSUE THREAD

**Issue by fif911** [KimMeen/Time-LLM#33]
Hi all

That's for your great work on this paper. I am working on a research in conflict prediction and want to try to extrapolate some historical datasets using your framework. I tried replicating it on my Mac M1 which failed misserably because I don't have NVIDIA GPU I assume 😂. 

Now I tried to run existing scripts using my ubuntu laptop that has 1040 NVIDIA GPU, but that also failed (I assume because lack of the space)

What was your set up for these experiments? Did you use conda to configure environment or just pip? I might be able to get access to a compute cluster of NVIDIA GPUs, but as they are costly I would like to get some details before I get to it.

Thanks in advance!

**Comment by fif911** [comment]
Also the paper does not mention how long it took to train for each dataset. Could you share these details please?

**Comment by kwuking** [comment]
> 1040 NVIDIA GPU,

You can install the corresponding dependencies by using pip install -r requirements.txt. The CUDA version for the 1040 NVIDIA GPU might be too old to be compatible with the current accelerate framework. You may try training with an A100.

**Comment by kwuking** [comment]
> Hi all
> 
> That's for your great work on this paper. I am working on a research in conflict prediction and want to try to extrapolate some historical datasets using your framework. I tried replicating it on my Mac M1 which failed misserably because I don't have NVIDIA GPU I assume 😂.
> 
> Now I tried to run existing scripts using my ubuntu laptop that has 1040 NVIDIA GPU, but that also failed (I assume because lack of the space)
> 
> What was your set up for these experiments? Did you use conda to configure environment or just pip? I might be able to get access to a compute cluster of NVIDIA GPUs, but as they are costly I would like to get some details before I get to it.
> 
> Thanks in advance!

You can install the corresponding dependencies by using pip install -r requirements.txt. The CUDA version for the 1040 NVIDIA GPU might be too old to be compatible with the current accelerate framework. You may try training with an A100.

**Comment by kwuking** [comment]
> Also the paper does not mention how long it took to train for each dataset. Could you share these details please?

Training time varies for different datasets due to their varying sizes, and this also depends on the model and quantity of your GPUs.

**Comment by fif911** [comment]
@kwuking I know. I am more curious about how long it took for the authors to train and which hardware did they use. Do you know these details?
