### ISSUE TITLE
Error when loading M4 training data

### ISSUE THREAD

**Issue by amayuelas** [KimMeen/Time-LLM#34]
When trying to load the M4 training data, it generates the following error: 

```
raining_values = np.array(                                                          
ValueError: setting an array element with a sequence. The requested array has an inhomoge
neous shape after 1 dimensions. The detected shape was (4227,) + inhomogeneous part.     
Traceback (most recent call last):                                                       
  File "/data5/aamayuelasfernandez/Time-LLM/run_m4.py", line 133, in <module>            
    train_data, train_loader = data_provider(args, 'train')                              
  File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_factory.py", line 46, in d
ata_provider                                                                             
    data_set = Data(                                                                     
  File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_loader.py", line 349, in _
_init__                                                                                  
    self.__read_data__()                                                                 
  File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_loader.py", line 357, in _
_read_data__                                                                 
```

I loaded the data separately and it gives the same error: 

```
Cell In[3], [line 4](vscode-notebook-cell:?execution_count=3&line=4)
      [1](vscode-notebook-cell:?execution_count=3&line=1) import numpy as np
      [2](vscode-notebook-cell:?execution_count=3&line=2) seasonal_patterns = 'Hourly'
----> [4](vscode-notebook-cell:?execution_count=3&line=4) training_values = np.array(
      [5](vscode-notebook-cell:?execution_count=3&line=5)             [v[~np.isnan(v)] for v in
      [6](vscode-notebook-cell:?execution_count=3&line=6)              dataset.values[dataset.groups == seasonal_patterns]])  # split different frequencies

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (414,) + inhomogeneous part.
```

I have debugged it a little and the files provided for M4 seem to have mixed lengths for a specific group/seasonal_pattern and therefore it cannot create the array.

Can you try to run it and M4 script and see if you run into the same issue?

**Comment by amayuelas** [comment]
I keep getting the very same error when I try to run the M4 script: 

And the 

```
train_data, train_loader = data_provider(args, 'train')
  File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_factory.py", line 34, in data_provider
    data_set = Data(
  File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_loader.py", line 335, in __init__
    self.__read_data__()
  File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_loader.py", line 343, in __read_data__
    training_values = np.array(
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48000,) + inhomogeneous part.
[2024-03-19 11:34:44,270] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3176791) of binary: /data5/aamayuelasfernandez/miniconda3/envs/tst/bin/python


Traceback (most recent call last):
  File "/data5/aamayuelasfernandez/miniconda3/envs/tst/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
    multi_gpu_launcher(args)
  File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
    distrib_run.run(args)
  File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

And the error seem to be when loading the training data from M4: 

`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48000,) + inhomogeneous part.`

I have checked and the error seem to be coming from the training data and not the valid/test data.

**Comment by Shi-Yuhong** [comment]
> I keep getting the very same error when I try to run the M4 script:
> 
> ```
> train_data, train_loader = data_provider(args, 'train')
>   File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_factory.py", line 34, in data_provider
>     data_set = Data(
>   File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_loader.py", line 335, in __init__
>     self.__read_data__()
>   File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_loader.py", line 343, in __read_data__
>     training_values = np.array(
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48000,) + inhomogeneous part.
> [2024-03-19 11:34:44,270] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3176791) of binary: /data5/aamayuelasfernandez/miniconda3/envs/tst/bin/python
> 
> 
> Traceback (most recent call last):
>   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
>     args.func(args)
>   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
>     multi_gpu_launcher(args)
>   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
>     distrib_run.run(args)
>   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
>     elastic_launch(
>   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ```
> 
> And the error seem to be when loading the training data from M4:
> 
> `ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48000,) + inhomogeneous part.`
> 
> I have checked and the error seem to be coming from the training data and not the valid/test data.

I have encountered the same problem. Could you tell me how can I solve it

**Comment by Shi-Yuhong** [comment]
> > I keep getting the very same error when I try to run the M4 script:
> > ```
> > train_data, train_loader = data_provider(args, 'train')
> >   File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_factory.py", line 34, in data_provider
> >     data_set = Data(
> >   File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_loader.py", line 335, in __init__
> >     self.__read_data__()
> >   File "/data5/aamayuelasfernandez/Time-LLM/data_provider/data_loader.py", line 343, in __read_data__
> >     training_values = np.array(
> > ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48000,) + inhomogeneous part.
> > [2024-03-19 11:34:44,270] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3176791) of binary: /data5/aamayuelasfernandez/miniconda3/envs/tst/bin/python
> > 
> > 
> > Traceback (most recent call last):
> >   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/bin/accelerate", line 8, in <module>
> >     sys.exit(main())
> >   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
> >     args.func(args)
> >   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
> >     multi_gpu_launcher(args)
> >   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
> >     distrib_run.run(args)
> >   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
> >     elastic_launch(
> >   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
> >     return launch_agent(self._config, self._entrypoint, list(args))
> >   File "/data5/aamayuelasfernandez/miniconda3/envs/tst/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
> >     raise ChildFailedError(
> > torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the error seem to be when loading the training data from M4:
> > `ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48000,) + inhomogeneous part.`
> > I have checked and the error seem to be coming from the training data and not the valid/test data.
> 
> I have encountered the same problem. Could you tell me how can I solve it

It seems that the solution under this [link](https://github.com/thuml/Time-Series-Library/issues/313) can solve the problem.
