### ISSUE TITLE
how many epochs to do some testing?

### ISSUE THREAD

**Issue by NickDatLe** [KimMeen/Time-LLM#36]
Hi there!

I want to train and run some test inference on the included datasets, are the weights already fine-tuned and ready to use with the included datasets or do I need to train it myself? If so, how many epochs? Thanks in advanced!

**Comment by kwuking** [comment]
> Hi there!
> 
> I want to train and run some test inference on the included datasets, are the weights already fine-tuned and ready to use with the included datasets or do I need to train it myself? If so, how many epochs? Thanks in advanced!

We express our sincere gratitude for your interest in our research. The foundational base model upon which Time-LLM is predicated has undergone prior pretraining. Consequently, it is requisite only to subject the reprogramming and output layer to training utilizing your dataset. For preliminary explorations, it is advisable to limit the training to 10 epochs or fewer to expedite the debugging process.

**Comment by NickDatLe** [comment]
> We express our sincere gratitude for your interest in our research. 
You're welcomed :)

> The foundational base model upon which Time-LLM is predicated has undergone prior pretraining. Consequently, it is requisite only to subject the reprogramming and output layer to training utilizing your dataset. 
Do you have the weights for verifying the results? Can I download the weights to test?

> For preliminary explorations, it is advisable to limit the training to 10 epochs or fewer to expedite the debugging process.
Is 10 epochs enough? The default in the code is 100. Again, if you provide the weights it would help us get similar results to your paper.

Keep up the great work!

**Comment by kwuking** [comment]
> > We express our sincere gratitude for your interest in our research.
> 
> You're welcomed :)
> 
> > The foundational base model upon which Time-LLM is predicated has undergone prior pretraining. Consequently, it is requisite only to subject the reprogramming and output layer to training utilizing your dataset.
> 
> Do you have the weights for verifying the results? Can I download the weights to test?
> 
The current positioning goal of Time-LLM is to serve as a universal framework that can adapt to different LLMs and PLMs, with the pre-trained weights still based on the respective LLM's weights.

> > For preliminary explorations, it is advisable to limit the training to 10 epochs or fewer to expedite the debugging process.
> 
> Is 10 epochs enough? The default in the code is 100. Again, if you provide the weights it would help us get similar results to your paper.
> 
For the complete training, please refer to the settings in the paper. As mentioned before, training for 10 epochs is only for preliminary exploration and convenient debugging.

**Comment by kwuking** [comment]
> > We express our sincere gratitude for your interest in our research.
> 
> You're welcomed :)
> 
> > The foundational base model upon which Time-LLM is predicated has undergone prior pretraining. Consequently, it is requisite only to subject the reprogramming and output layer to training utilizing your dataset.
> 
> Do you have the weights for verifying the results? Can I download the weights to test?
> 

We are continuously exploring the foundational models for time series forecasting. Our latest work is also attempting to perform complete pre-training of the foundational model from scratch. However, considering the need to consume vast resources and the necessity to experiment with new model structures and framework designs, we are currently still in the exploration phase. In the future, we will release model code and pre-trained weights that are fully based on the huggingface.
