### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by haojie-coder** [KimMeen/Time-LLM#37]
for i, x, x_mark in zip(range(len(x_enc)), x_enc, x_mark_enc):
                B, T, N = x.size()
                x = self.normalize_layers[i](x, 'norm')
                if self.channel_independent:
                    x = x.permute(0, 2, 1).contiguous().reshape(B * N, T, 1)
                x_list.append(x)
             

 x.size()=2，how can B, T, N = x.size() ？

**Comment by kwuking** [comment]
x_enc needs to include three dimensions, namely the batch dimension B, the time step dimension T, and the input dimension N. Please check if the input variable meets this requirement.
