### ISSUE TITLE
Problem of custom data utilization when new column added

### ISSUE THREAD

**Issue by Maydaytyh** [KimMeen/Time-LLM#39]
Hi,

Thanks for the great work.
I would like to apply this work to our own data. However, our data includes an extra column, labelled as 'code'. An example can be seen in the image below. Could you please advise on how to modify the process to accommodate this extra column? Thank you.
<img width="733" alt="image" src="https://github.com/KimMeen/Time-LLM/assets/13815598/eda8157b-86c5-416b-9a1d-c125df2d9b60">

**Comment by kwuking** [comment]
Is the 'code' column in your dataset meant to represent different time series? If it denotes different series (for example, HUFL, OT), you can perform a Cartesian product with it and other series to generate distinct series for individual predictions (such as HUFL-1, HUFL-2, OT-1, OT-2). If not, you will need to further elaborate on what the function of this new column is.

**Comment by Maydaytyh** [comment]
> Is the 'code' column in your dataset meant to represent different time series? If it denotes different series (for example, HUFL, OT), you can perform a Cartesian product with it and other series to generate distinct series for individual predictions (such as HUFL-1, HUFL-2, OT-1, OT-2). If not, you will need to further elaborate on what the function of this new column is.

Thank you for your reply!
Yes, the code means different time series. If I add this column to ETTm1, this column means different places. 
I can understand your way but the code may have a large value. 
For example, it can be 10000, so the Cartesian product may be difficult. 
Can I complete this task in other ways? What needs to be changed? Is it mainly the data processing part?
Thank you！

**Comment by kwuking** [comment]
> > Is the 'code' column in your dataset meant to represent different time series? If it denotes different series (for example, HUFL, OT), you can perform a Cartesian product with it and other series to generate distinct series for individual predictions (such as HUFL-1, HUFL-2, OT-1, OT-2). If not, you will need to further elaborate on what the function of this new column is.
> 
> Thank you for your reply! Yes, the code means different time series. If I add this column to ETTm1, this column means different places. I can understand your way but the code may have a large value. For example, it can be 10000, so the Cartesian product may be difficult. Can I complete this task in other ways? What needs to be changed? Is it mainly the data processing part? Thank you！

Yes, you only need the data_factory.py and data_loader.py files. However, preprocessing of the data is essential; you need to flatten the different time series first before you can proceed with the prediction.

**Comment by Maydaytyh** [comment]
> > > Is the 'code' column in your dataset meant to represent different time series? If it denotes different series (for example, HUFL, OT), you can perform a Cartesian product with it and other series to generate distinct series for individual predictions (such as HUFL-1, HUFL-2, OT-1, OT-2). If not, you will need to further elaborate on what the function of this new column is.
> > 
> > 
> > Thank you for your reply! Yes, the code means different time series. If I add this column to ETTm1, this column means different places. I can understand your way but the code may have a large value. For example, it can be 10000, so the Cartesian product may be difficult. Can I complete this task in other ways? What needs to be changed? Is it mainly the data processing part? Thank you！
> 
> Yes, you only need the data_factory.py and data_loader.py files. However, preprocessing of the data is essential; you need to flatten the different time series first before you can proceed with the prediction.

Thank you! 
What form should I process the data into? Is the form in the previous picture ok? 
I add my dataset to data_factory.data_dict and create a new class in data_loader.py imitating  the Dataset_ETT_minute class. But I'm not sure what I should modify in the `__read_data__` and `__getitem__`. Could you help me? Thank you !!

**Comment by kwuking** [comment]
> __getitem__

First, you need to flatten all different sequences in data preprocessing, meaning each of your columns should correspond to different time series. Then, you can refer to the existing read_data and getitem in the data_loader.

**Comment by kwuking** [comment]
> > > > Is the 'code' column in your dataset meant to represent different time series? If it denotes different series (for example, HUFL, OT), you can perform a Cartesian product with it and other series to generate distinct series for individual predictions (such as HUFL-1, HUFL-2, OT-1, OT-2). If not, you will need to further elaborate on what the function of this new column is.
> > > 
> > > 
> > > Thank you for your reply! Yes, the code means different time series. If I add this column to ETTm1, this column means different places. I can understand your way but the code may have a large value. For example, it can be 10000, so the Cartesian product may be difficult. Can I complete this task in other ways? What needs to be changed? Is it mainly the data processing part? Thank you！
> > 
> > 
> > Yes, you only need the data_factory.py and data_loader.py files. However, preprocessing of the data is essential; you need to flatten the different time series first before you can proceed with the prediction.
> 
> Thank you! What form should I process the data into? Is the form in the previous picture ok? I add my dataset to data_factory.data_dict and create a new class in data_loader.py imitating the Dataset_ETT_minute class. But I'm not sure what I should modify in the `__read_data__` and `__getitem__`. Could you help me? Thank you !!

First, you need to flatten all different sequences in data preprocessing, meaning each of your columns should correspond to different time series. Then, you can refer to the existing read_data and getitem in the data_loader.

**Comment by Maydaytyh** [comment]
> > > > > Is the 'code' column in your dataset meant to represent different time series? If it denotes different series (for example, HUFL, OT), you can perform a Cartesian product with it and other series to generate distinct series for individual predictions (such as HUFL-1, HUFL-2, OT-1, OT-2). If not, you will need to further elaborate on what the function of this new column is.
> > > > 
> > > > 
> > > > Thank you for your reply! Yes, the code means different time series. If I add this column to ETTm1, this column means different places. I can understand your way but the code may have a large value. For example, it can be 10000, so the Cartesian product may be difficult. Can I complete this task in other ways? What needs to be changed? Is it mainly the data processing part? Thank you！
> > > 
> > > 
> > > Yes, you only need the data_factory.py and data_loader.py files. However, preprocessing of the data is essential; you need to flatten the different time series first before you can proceed with the prediction.
> > 
> > 
> > Thank you! What form should I process the data into? Is the form in the previous picture ok? I add my dataset to data_factory.data_dict and create a new class in data_loader.py imitating the Dataset_ETT_minute class. But I'm not sure what I should modify in the `__read_data__` and `__getitem__`. Could you help me? Thank you !!
> 
> First, you need to flatten all different sequences in data preprocessing (it's important to note that this part of the process should be done before you use this set of code), meaning each of your columns should correspond to the different time series. Then, you can refer to the existing **read_data** and **getitem** in the data_loader.

Sorry, I didn't fully understand you. Does `meaning each of your columns should correspond to the different time series. ` mean that when all time series are merged together, each column attribute should clearly belong to which time series? Just like this?
<img width="1250" alt="image" src="https://github.com/KimMeen/Time-LLM/assets/13815598/aaec18cd-80e6-4a11-8598-2269cd107db6">

**Comment by kwuking** [comment]
> > > > > > Is the 'code' column in your dataset meant to represent different time series? If it denotes different series (for example, HUFL, OT), you can perform a Cartesian product with it and other series to generate distinct series for individual predictions (such as HUFL-1, HUFL-2, OT-1, OT-2). If not, you will need to further elaborate on what the function of this new column is.
> > > > > 
> > > > > 
> > > > > Thank you for your reply! Yes, the code means different time series. If I add this column to ETTm1, this column means different places. I can understand your way but the code may have a large value. For example, it can be 10000, so the Cartesian product may be difficult. Can I complete this task in other ways? What needs to be changed? Is it mainly the data processing part? Thank you！
> > > > 
> > > > 
> > > > Yes, you only need the data_factory.py and data_loader.py files. However, preprocessing of the data is essential; you need to flatten the different time series first before you can proceed with the prediction.
> > > 
> > > 
> > > Thank you! What form should I process the data into? Is the form in the previous picture ok? I add my dataset to data_factory.data_dict and create a new class in data_loader.py imitating the Dataset_ETT_minute class. But I'm not sure what I should modify in the `__read_data__` and `__getitem__`. Could you help me? Thank you !!
> > 
> > 
> > First, you need to flatten all different sequences in data preprocessing (it's important to note that this part of the process should be done before you use this set of code), meaning each of your columns should correspond to the different time series. Then, you can refer to the existing **read_data** and **getitem** in the data_loader.
> 
> Sorry, I didn't fully understand you. Does `meaning each of your columns should correspond to the different time series. ` mean that when all time series are merged together, each column attribute should clearly belong to which time series? Just like this? <img alt="image" width="1250" src="https://private-user-images.githubusercontent.com/13815598/313698316-aaec18cd-80e6-4a11-8598-2269cd107db6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzE2MDYsIm5iZiI6MTcxMDc3MTMwNiwicGF0aCI6Ii8xMzgxNTU5OC8zMTM2OTgzMTYtYWFlYzE4Y2QtODBlNi00YTExLTg1OTgtMjI2OWNkMTA3ZGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE0MTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZDg1ZGJhNmQwNGQ0MzhmMmU1NzMzOThmZTNlN2Q0OTkyZjFkYjVmMDZkMTQ0MjE5ZWI2OGZkNTkzNWJjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_9oPk53i-w-74z7p8aeOgOIApUds6wbYJINY36iCvA">

Your understanding is correct. The current framework is designed based on the Time-Series-Library, primarily supporting univariate and multivariate time series forecasting. For your use case of employing specific columns to identify different time series data, we have designed a brand new framework to address such issues in our latest work. Please stay tuned.

**Comment by Maydaytyh** [comment]
> > > > > > > Is the 'code' column in your dataset meant to represent different time series? If it denotes different series (for example, HUFL, OT), you can perform a Cartesian product with it and other series to generate distinct series for individual predictions (such as HUFL-1, HUFL-2, OT-1, OT-2). If not, you will need to further elaborate on what the function of this new column is.
> > > > > > 
> > > > > > 
> > > > > > Thank you for your reply! Yes, the code means different time series. If I add this column to ETTm1, this column means different places. I can understand your way but the code may have a large value. For example, it can be 10000, so the Cartesian product may be difficult. Can I complete this task in other ways? What needs to be changed? Is it mainly the data processing part? Thank you！
> > > > > 
> > > > > 
> > > > > Yes, you only need the data_factory.py and data_loader.py files. However, preprocessing of the data is essential; you need to flatten the different time series first before you can proceed with the prediction.
> > > > 
> > > > 
> > > > Thank you! What form should I process the data into? Is the form in the previous picture ok? I add my dataset to data_factory.data_dict and create a new class in data_loader.py imitating the Dataset_ETT_minute class. But I'm not sure what I should modify in the `__read_data__` and `__getitem__`. Could you help me? Thank you !!
> > > 
> > > 
> > > First, you need to flatten all different sequences in data preprocessing (it's important to note that this part of the process should be done before you use this set of code), meaning each of your columns should correspond to the different time series. Then, you can refer to the existing **read_data** and **getitem** in the data_loader.
> > 
> > 
> > Sorry, I didn't fully understand you. Does `meaning each of your columns should correspond to the different time series. ` mean that when all time series are merged together, each column attribute should clearly belong to which time series? Just like this? <img alt="image" width="1250" src="https://private-user-images.githubusercontent.com/13815598/313698316-aaec18cd-80e6-4a11-8598-2269cd107db6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzE2MDYsIm5iZiI6MTcxMDc3MTMwNiwicGF0aCI6Ii8xMzgxNTU5OC8zMTM2OTgzMTYtYWFlYzE4Y2QtODBlNi00YTExLTg1OTgtMjI2OWNkMTA3ZGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE0MTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZDg1ZGJhNmQwNGQ0MzhmMmU1NzMzOThmZTNlN2Q0OTkyZjFkYjVmMDZkMTQ0MjE5ZWI2OGZkNTkzNWJjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_9oPk53i-w-74z7p8aeOgOIApUds6wbYJINY36iCvA">
> 
> Your understanding is correct. The current framework is designed based on the Time-Series-Library, primarily supporting univariate and multivariate time series forecasting. For your use case of employing specific columns to identify different time series data, we have designed a brand new framework to address such issues in our latest work. Please stay tuned.

Thanks a lot. Can I think that I can't keep the (code, data, features, target) structure in the training process? My purpose is to make the code useful. And I'm looking forward to your new work!

**Comment by kwuking** [comment]
> > > > > > > > Is the 'code' column in your dataset meant to represent different time series? If it denotes different series (for example, HUFL, OT), you can perform a Cartesian product with it and other series to generate distinct series for individual predictions (such as HUFL-1, HUFL-2, OT-1, OT-2). If not, you will need to further elaborate on what the function of this new column is.
> > > > > > > 
> > > > > > > 
> > > > > > > Thank you for your reply! Yes, the code means different time series. If I add this column to ETTm1, this column means different places. I can understand your way but the code may have a large value. For example, it can be 10000, so the Cartesian product may be difficult. Can I complete this task in other ways? What needs to be changed? Is it mainly the data processing part? Thank you！
> > > > > > 
> > > > > > 
> > > > > > Yes, you only need the data_factory.py and data_loader.py files. However, preprocessing of the data is essential; you need to flatten the different time series first before you can proceed with the prediction.
> > > > > 
> > > > > 
> > > > > Thank you! What form should I process the data into? Is the form in the previous picture ok? I add my dataset to data_factory.data_dict and create a new class in data_loader.py imitating the Dataset_ETT_minute class. But I'm not sure what I should modify in the `__read_data__` and `__getitem__`. Could you help me? Thank you !!
> > > > 
> > > > 
> > > > First, you need to flatten all different sequences in data preprocessing (it's important to note that this part of the process should be done before you use this set of code), meaning each of your columns should correspond to the different time series. Then, you can refer to the existing **read_data** and **getitem** in the data_loader.
> > > 
> > > 
> > > Sorry, I didn't fully understand you. Does `meaning each of your columns should correspond to the different time series. ` mean that when all time series are merged together, each column attribute should clearly belong to which time series? Just like this? <img alt="image" width="1250" src="https://private-user-images.githubusercontent.com/13815598/313698316-aaec18cd-80e6-4a11-8598-2269cd107db6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzE2MDYsIm5iZiI6MTcxMDc3MTMwNiwicGF0aCI6Ii8xMzgxNTU5OC8zMTM2OTgzMTYtYWFlYzE4Y2QtODBlNi00YTExLTg1OTgtMjI2OWNkMTA3ZGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE0MTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZDg1ZGJhNmQwNGQ0MzhmMmU1NzMzOThmZTNlN2Q0OTkyZjFkYjVmMDZkMTQ0MjE5ZWI2OGZkNTkzNWJjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_9oPk53i-w-74z7p8aeOgOIApUds6wbYJINY36iCvA">
> > 
> > 
> > Your understanding is correct. The current framework is designed based on the Time-Series-Library, primarily supporting univariate and multivariate time series forecasting. For your use case of employing specific columns to identify different time series data, we have designed a brand new framework to address such issues in our latest work. Please stay tuned.
> 
> Thanks a lot. Can I think that I can't keep the (code, data, features, target) structure in the training process? My purpose is to make the code useful. And I'm looking forward to your new work!

Yes, you need to maintain consistency with the structure of other datasets (such as ETT, etc.), where each column primarily identifies different time series.
