### ISSUE TITLE
Error when installing Scipy

### ISSUE THREAD

**Issue by benzitzewitz01** [KimMeen/Time-LLM#40]
When I install scipy, I get an error that wheels can't be built for numpy. I can't seem to fix this error using the methods I find online. Any advice?

**Comment by kwuking** [comment]
> When I install scipy, I get an error that wheels can't be built for numpy. I can't seem to fix this error using the methods I find online. Any advice?

What version of Python are you using? It is recommended that you create a new Python virtual environment for installing the necessary dependencies to avoid potential conflicts.

**Comment by benzitzewitz01** [comment]
I'm on Python 3.11.4 and I'm doing this in a venv. If I use a more recent version of scipy, like 1.9.2, it works fine. However, I still run into problems with deepspeed

**Comment by dahani9091** [comment]
I had the same issue before, use python 3.9 and install these libraries versions. it will work.

pip install deepspeed==0.10.0 accelerate==0.21.0 einops==0.7.0 tqdm==4.65.0 peft==0.4.0 transformers==4.29.2
pip install reformer-pytorch==1.4.4 torch==2.0.1  numpy==1.24.3 matplotlib==3.7.0
pip install scikit_learn==1.2.2 pandas==1.5.3 scipy==1.5.4
