### ISSUE TITLE
About the pre-trained word embeddings

### ISSUE THREAD

**Issue by YuanYuan98** [KimMeen/Time-LLM#43]
Hi, thanks for releasing the code of this excellent work! The idea of Patch Reprogramming is very interesting.

I do have a question regarding the pre-trained word embeddings (vocabulary) $E$ used in your work. Could you please clarify the scale of the considered vocabulary?

**Comment by kwuking** [comment]
> Hi, thanks for releasing the code of this excellent work! The idea of Patch Reprogramming is very interesting.
> 
> I do have a question regarding the pre-trained word embeddings (vocabulary) E used in your work. Could you please clarify the scale of the considered vocabulary?

hi, the size of the vocabulary we fully use is determined by the specific LLM base. Different LLM bases have different sizes, so you can refer to the LLM you want to use for specifics.
