### ISSUE TITLE
Prompt vs no prompt results?

### ISSUE THREAD

**Issue by willxxy** [KimMeen/Time-LLM#46]
Hello,

Thank you for the great work. I was wondering if there was any prior experiments that you did without the prompts? 
I am wondering how much the prompts may help. 

Thank you.

**Comment by kwuking** [comment]
hi, you can refer to the ablation experiment results in the paper, where we provide an analysis of the impact of prompts on prediction results.

**Comment by willxxy** [comment]
I found the relevant section in the paper. Sorry about the misunderstanding. Thank you!  Will close this issue now.

**Comment by kwuking** [comment]
> I found the relevant section in the paper. Sorry about the misunderstanding. Thank you! Will close this issue now.



> I found the relevant section in the paper. Sorry about the misunderstanding. Thank you! Will close this issue now.

Thank you for your attention to our work.
