### ISSUE TITLE
forecasting using a saved model

### ISSUE THREAD

**Issue by HamBa-m** [KimMeen/Time-LLM#47]
is there a tutorial on how to use a saved checkpoint to forecast on new data ?

**Comment by HamBa-m** [comment]
something like this (from the paper appendix)
![image](https://github.com/KimMeen/Time-LLM/assets/62408114/4bd55403-a901-43aa-a9b4-622af420679f)

**Comment by kwuking** [comment]
hi, you can refer to the model save and load methods of huggingface accelerator for processing.
![image](https://github.com/KimMeen/Time-LLM/assets/7886135/4903af26-9771-41de-abc8-78eb0e7bede7)

**Comment by kwuking** [comment]
> is there a tutorial on how to use a saved checkpoint to forecast on new data ?
You can refer to the operation of loading the model, after training is completed, load the model to test it on a new dataset.

![image](https://github.com/KimMeen/Time-LLM/assets/7886135/9b3a9e84-4111-4364-9d72-1a5a49d933e4)

**Comment by HamBa-m** [comment]
what about forecasting ? I can't really tell how to use the method ```forecast()``` of the class TimeLLM

**Comment by kwuking** [comment]
> what about forecasting ? I can't really tell how to use the method `forecast()` of the class TimeLLM

After you have completed model training, you can directly call the forward method of TimeLLM for prediction, as shown in the following figure:

![image](https://github.com/KimMeen/Time-LLM/assets/7886135/159c474a-7998-4c80-bf38-6a965e0bdad8)

**Comment by HamBa-m** [comment]
i used this script to generate forecast based on a trained model:

```[python]
# Predict and plot the predictions
with torch.no_grad():
    predictions = []
    actuals = []
    for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(test_loader)):
        batch_x = batch_x.float().to(accelerator.device)
        batch_x_mark = batch_x_mark.float().to(accelerator.device)

        # decoder input
        dec_inp = torch.zeros_like(batch_y[:, -args.pred_len:, :]).float().to(
            accelerator.device)
        dec_inp = torch.cat([batch_y[:, :args.label_len, :], dec_inp], dim=1).float().to(
            accelerator.device)

        # Predict
        if args.output_attention:
            outputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark)[0]
        else:
            outputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark)

        # Process the predictions
        f_dim = -1 if args.features == 'MS' else 0
        outputs = outputs[:, -args.pred_len:, f_dim:]
        pred = outputs.detach().cpu().numpy()
        actual = batch_y[:, -args.pred_len:, f_dim:].detach().cpu().numpy()
        predictions.append(pred)
        actuals.append(actual)

    # Concatenate the predictions
    predictions = np.concatenate(predictions, axis=0)

    # Concatenate the actual data
    actuals = np.concatenate(actuals, axis=0)```

**Comment by praneshvyas11** [comment]
I'm facing a challenge with loading a trained model and forecasting it. I'm forecasting with `M` setup (multi-variate)

@HamBa-m - did you get the above code snipper to work for forecasting?

Also, how did you associate the forecast to a specific time-series in your input?

**Comment by HamBa-m** [comment]
@praneshvyas11 Yes, it worked for me on another dataset I was working on. I'll be making a pull request soon to the repository where I made a clear tutorial on how to forecast using a trained model on a custom dataset.

**Comment by valentynariabchuk** [comment]
> @praneshvyas11 Yes, it worked for me on another dataset I was working on. I'll be making a pull request soon to the repository where I made a clear tutorial on how to forecast using a trained model on a custom dataset, as well as an additional bash script to forecast.

Hi, if you can share it, this would be amazing! Could you however inform, when you are going to upload it? (or if you did that already, share the link).

**Comment by HarrywillDr** [comment]
> @praneshvyas11 Yes, it worked for me on another dataset I was working on. I'll be making a pull request soon to the repository where I made a clear tutorial on how to forecast using a trained model on a custom dataset, as well as an additional bash script to forecast.

Hi, thank you for you kind work!. may I ask whether you share the tutorial already,pls?

**Comment by mozeqiu123** [comment]
> @praneshvyas11 Yes, it worked for me on another dataset I was working on. I'll be making a pull request soon to the repository where I made a clear tutorial on how to forecast using a trained model on a custom dataset, as well as an additional bash script to forecast.

Hi, thank you for you kind work!. may I ask whether you share the tutorial already,pls?

**Comment by Huang-Jingxiang** [comment]
Maybe this will helps. https://towardsdatascience.com/time-llm-reprogram-an-llm-for-time-series-forecasting-e2558087b8ac

**Comment by JackKoLing** [comment]
> @praneshvyas11 Yes, it worked for me on another dataset I was working on. I'll be making a pull request soon to the repository where I made a clear tutorial on how to forecast using a trained model on a custom dataset, as well as an additional bash script to forecast.

Hi, cool, is there any progress?

**Comment by huynhkhoa44** [comment]
I would like to ask if there is any code or scripts for inference with a model trained on a custom dataset. If not, what is the best way to do it now?
Note that I want the inference with checkpoint directly from this github link, not the inference from NeuralForecast.

**Comment by Med-Rokaimi** [comment]
@HamBa-m 
Can you please share your code?
