### ISSUE TITLE
difference between main_run.py and main_pretrain.py

### ISSUE THREAD

**Issue by HamBa-m** [KimMeen/Time-LLM#49]
I tried hard to notice the difference between the files main_run and main_pretrain, but I can't say but they are the same with very small differences that mainly doesn't affect the logic of the codes. Could we get any enlightenment in this context ?

**Comment by kwuking** [comment]
> main_pretrain


> I tried hard to notice the difference between the files main_run and main_pretrain, but I can't say but they are the same with very small differences that mainly doesn't affect the logic of the codes. Could we get any enlightenment in this context ?

hi, main_run is mainly used for long-term forecasting experiments, while main_pretrain is convenient for zero-shot experiments. Most of the content between the two is indeed shared.
