### ISSUE TITLE
pip install requirements is failing

### ISSUE THREAD

**Issue by bruciebruce** [KimMeen/Time-LLM#5]
On Ubuntu 23.10 I cannot run your pip install.

Error log is very long and have attached it. 

Do I need to install mkl in a separate step?

[time-llm-pip-error-log.txt](https://github.com/KimMeen/Time-LLM/files/14316086/time-llm-pip-error-log.txt)

**Comment by bruciebruce** [comment]
I was using python 3.11
I switched to 3.9 but then got errors installing torch 2.0.1.  I manually installed torch 2.0.2 at the terminal and then ran the pip requirements again.  It now installed torch 2.0.1 and then uninstalled torch 2.0.2  
Everything is good now.

**Comment by bruciebruce** [comment]
Closing this.

**Comment by benzitzewitz01** [comment]
was this error also with deepspeed or just torch?

**Comment by bruciebruce** [comment]
As far as I can tell it was the fact that at the time this project required Python 3.9.  The issue with torch resolved itself after switching to 3.9  I did not have an issue with deepspeed.
