### ISSUE TITLE
Using FP16

### ISSUE THREAD

**Issue by benzitzewitz01** [KimMeen/Time-LLM#50]
If I have to change the precision to FP16 to accomodate my GPU, are there other changes I have to make? I changed the mixed precision flag and the DS config json shown below.

![Screenshot 2024-03-27 154651](https://github.com/KimMeen/Time-LLM/assets/130809372/48cf244d-354c-4c3b-a8c7-aec75cc4ad99)

**Comment by benzitzewitz01** [comment]
I also get this error 
![image](https://github.com/KimMeen/Time-LLM/assets/130809372/79ffc6b0-58eb-4aaf-a67f-a653b8be5cc4)

**Comment by kwuking** [comment]
> If I have to change the precision to FP16 to accomodate my GPU, are there other changes I have to make? I changed the mixed precision flag and the DS config json shown below.
> 
> ![Screenshot 2024-03-27 154651](https://private-user-images.githubusercontent.com/130809372/317512627-48cf244d-354c-4c3b-a8c7-aec75cc4ad99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTM3NzYsIm5iZiI6MTcxMTYxMzQ3NiwicGF0aCI6Ii8xMzA4MDkzNzIvMzE3NTEyNjI3LTQ4Y2YyNDRkLTM1NGMtNGMzYi1hOGM3LWFlYzc1Y2M0YWQ5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwODExMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjJiYjA3NGRmNDFhNTc5NzRiYTFlYTZmZmE4MTkyZmFhYThhMDBjNDUxNDI1Y2NiZmE2NDE5MjgxYzBkMTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QmOFNYxUTXZupKP9-zbvMyA983FtsDp-4P3up9p-PH0)

It is recommended to train using bf16 precision, as this can better adapt to foundation models like LLAMA.

**Comment by kwuking** [comment]
> I also get this error ![image](https://private-user-images.githubusercontent.com/130809372/317513028-79ffc6b0-58eb-4aaf-a67f-a653b8be5cc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTM3NzYsIm5iZiI6MTcxMTYxMzQ3NiwicGF0aCI6Ii8xMzA4MDkzNzIvMzE3NTEzMDI4LTc5ZmZjNmIwLTU4ZWItNGFhZi1hNjdmLWE2NTNiOGJlNWNjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwODExMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTUxODE4MTdmNWY0NzU3M2M1N2ZiNWE4MWUwYjA0MDAxMTJmMWEzMGU1ZmYxYjkzZmIzZmIyMGVjZjEwYmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yvpmHwl2EvNytXkpyoSFRljJP_oawIvQX8xKQZS5aZE)



> I also get this error ![image](https://private-user-images.githubusercontent.com/130809372/317513028-79ffc6b0-58eb-4aaf-a67f-a653b8be5cc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTM3NzYsIm5iZiI6MTcxMTYxMzQ3NiwicGF0aCI6Ii8xMzA4MDkzNzIvMzE3NTEzMDI4LTc5ZmZjNmIwLTU4ZWItNGFhZi1hNjdmLWE2NTNiOGJlNWNjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwODExMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTUxODE4MTdmNWY0NzU3M2M1N2ZiNWE4MWUwYjA0MDAxMTJmMWEzMGU1ZmYxYjkzZmIzZmIyMGVjZjEwYmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yvpmHwl2EvNytXkpyoSFRljJP_oawIvQX8xKQZS5aZE)

The error you encountered, as shown in the figure, is related to data loading. Please check if the data files are correct and if the versions of pandas and other dependencies meet the requirements.

**Comment by JunJ-H-hub** [comment]
I encountered the same problem. How did you finally solve it?
