### ISSUE TITLE
script failed on single GPU 

### ISSUE THREAD

**Issue by yangboz** [KimMeen/Time-LLM#52]
when running  bash ./scripts/TimeLLM_ETTh1.sh 
```
[2024-03-28 16:36:25,314] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-03-28 16:36:26.899060: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-28 16:36:26.901427: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
```

my env info:

Linux hp 5.15.0-97-generic #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2 

thanks

**Comment by kwuking** [comment]
> when running bash ./scripts/TimeLLM_ETTh1.sh
> 
> ```
> [2024-03-28 16:36:25,314] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> 2024-03-28 16:36:26.899060: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 2024-03-28 16:36:26.901427: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
> ```
> 
> my env info:
> 
> Linux hp 5.15.0-97-generic #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
> 
> 
> | NVIDIA-SMI 535.154.05 Driver Version: 535.154.05 CUDA Version: 12.2
> 
> thanks

Hi, we are currently using the Hugging Face Accelerator framework for multi-GPU distributed training, requiring 8 GPUs. If you wish to use a single GPU, please remove the dependency on the Accelerator framework or reduce the num_process parameter in the script to match the number of your GPUs.

**Comment by NickDatLe** [comment]
You can also configure accelerate to use 1 GPU, I've done it on my gaming PC and it works.
Get rid of the --multi_gpu flag, num_process should be removed or set to 1 and make sure to update the batch size to the VRAM limits of your single GPU. Obviously it's not practical to train with 1 GPU, but you can at least run inference.

**Comment by stupidoge** [comment]
@NickDatLe  Hi, I wonder whether a 4090 GPU with 20G memory could train this model? I wanna debug the codes input and output by debugging/running run_main.py. If that is not possible, do you know how to change the model into GPT2? ( I cannot see any scripts related to GPT) 

Regards

**Comment by stupidoge** [comment]
> You can also configure accelerate to use 1 GPU, I've done it on my gaming PC and it works. Get rid of the --multi_gpu flag, num_process should be removed or set to 1 and make sure to update the batch size to the VRAM limits of your single GPU. Obviously it's not practical to train with 1 GPU, but you can at least run inference.

@NickDatLe Hi, it seems 4090 cannot load this mode, I give up. Hopefully, I could reproduce by using GPT2. However, could I ask you a question? May I know how what is the difference between run_main.py and run_pretrain.py? Should we run pretrain at first (it might be text prototype matching?)

It seems run_main.py has no difference with GPT4TS(One Fits All)

**Comment by yangboz** [comment]
> @NickDatLe Hi, I wonder whether a 4090 GPU with 20G memory could train this model? I wanna debug the codes input and output by debugging/running run_main.py. If that is not possible, do you know how to change the model into GPT2? ( I cannot see any scripts related to GPT)
> 
> Regards

only 16G  GPU now :-(

**Comment by stupidoge** [comment]
Try gpt2, it worked. I think we could communicate together, would mind to share me your wechat or email&nbsp;



from&nbsp;qq&nbsp;email


------------------ Original ------------------
From: yangbo.zhou ***@***.***&gt;
Date: Fri,Mar 29,2024 5:03 PM
To: KimMeen/Time-LLM ***@***.***&gt;
Cc: Kai ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [KimMeen/Time-LLM] script failed on single GPU  (Issue #52)





  
@NickDatLe Hi, I wonder whether a 4090 GPU with 20G memory could train this model? I wanna debug the codes input and output by debugging/running run_main.py. If that is not possible, do you know how to change the model into GPT2? ( I cannot see any scripts related to GPT)
 
Regards
  
only 16G  GPU now :-(

**Comment by yangboz** [comment]
> Try gpt2, it worked. I think we could communicate together, would mind to share me your wechat or email&nbsp; from&nbsp;qq&nbsp;email
> […](#)

my Wechat ID is 17610195566, thanks.

**Comment by NickDatLe** [comment]
> @NickDatLe Hi, I wonder whether a 4090 GPU with 20G memory could train this model? I wanna debug the codes input and output by debugging/running run_main.py. If that is not possible, do you know how to change the model into GPT2? ( I cannot see any scripts related to GPT)
> 
> Regards

Yes, try lowering the batch size to 1.

**Comment by yangboz** [comment]
or , is it possible running pm MAC M 1 16G memory ?

**Comment by valentynariabchuk** [comment]
> You can also configure accelerate to use 1 GPU, I've done it on my gaming PC and it works. Get rid of the --multi_gpu flag, num_process should be removed or set to 1 and make sure to update the batch size to the VRAM limits of your single GPU. Obviously it's not practical to train with 1 GPU, but you can at least run inference.

Hi, did you train Llama with single GPU or only GPT2? How long did it take to train it? (could you please also provide the information on how big were you datasets).
