### ISSUE TITLE
Running on python 3.11

### ISSUE THREAD

**Issue by NickDatLe** [KimMeen/Time-LLM#54]
hi @kwuking - I got the code working with python 3.11. I'm still testing all of the scripts, but would you want the updated code once I'm done testing? Python 3.11 is about 100% faster than python 3.9, so it'll save you and other people who are training time and money.

**Comment by kwuking** [comment]
> hi @kwuking - I got the code working with python 3.11. I'm still testing all of the scripts, but would you want the updated code once I'm done testing? Python 3.11 is about 100% faster than python 3.9, so it'll save you and other people who are training time and money.

Thank you very much for your support in our work. It's really great. Regarding the issue you raised about modifying the Python version, we suggest that you submit a corresponding pull request. We will merge and handle it. Your discovery is highly appreciated, and it is very important for us to collectively advance the research on Time-LLM. Once again, we express our gratitude and appreciation to you.

**Comment by NickDatLe** [comment]
see https://github.com/KimMeen/Time-LLM/pull/57

**Comment by mariozupan** [comment]
In docker, image python 3.9 I can install pytorch and requirements, but I am getting:
TypeError: 'NoneType' object is not subscriptable
when I starts any of script quick demos.

I also tried to install in venv environment, with python 3.11 but requirements failed to install with:

ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
      
      
      So, did you submit 3.11 friendly version on a main branch?

**Comment by mariozupan** [comment]
Maybe this is also important:
python3.11/cpython/unicodeobject.h:600:42: note: declared here
              600 | Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
                  |                                          ^~~~~~~~~~~~~~~~~~~~~

**Comment by KimMeen** [comment]
Hello folks,

We have merged PR #57 to the main branch. Thank you @NickDatLe.

I executed several tests on my end, and there were maximum 5% epoch time and 10%-20% GPU memory consumption deduction. Below are my environment configurations FYI.

**Config. 1**
python==3.8.5
torch==2.0.1 with CUDA 11.7
accelerate==0.21.0
deepspeed==0.10.1
transformer==4.28.1
numpy==1.19.2
pandas==1.2.2

**Config. 2** was what @NickDatLe suggested with python 3.11 (but I used cuda 11.8 on my end)

Please let us know if you have further suggestions/questions 🤗
