### ISSUE TITLE
Question about ETT dataset

### ISSUE THREAD

**Issue by Maydaytyh** [KimMeen/Time-LLM#55]
In `data_loader.py`, I found that only 20 months' data has been used. And I wanna to ask why not using all data?
Thank you!
<img width="1067" alt="image" src="https://github.com/KimMeen/Time-LLM/assets/13815598/e69fa611-a0ff-42bc-8bc4-bc58f4fb2aab">

**Comment by kwuking** [comment]
> In `data_loader.py`, I found that only 20 months' data has been used. And I wanna to ask why not using all data? Thank you! <img alt="image" width="1067" src="https://private-user-images.githubusercontent.com/13815598/318346560-e69fa611-a0ff-42bc-8bc4-bc58f4fb2aab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTM4OTksIm5iZiI6MTcxMTk1MzU5OSwicGF0aCI6Ii8xMzgxNTU5OC8zMTgzNDY1NjAtZTY5ZmE2MTEtYTBmZi00MmJjLThiYzQtYmM1OGY0ZmIyYWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2Mzk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYTllZTNiOGExODViZDUyN2EwZmQ2MmYzY2E0YzhhYzhlMzc4ZDE1MGJjMWVhYzU4ZjQ3NzM3NTgxNDdiZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WERWm_4SZHTnbClsrsis4NlZ_qhhtBIvHwE1XhVOUvw">

Hi, here we are referencing the settings of the Time Series Library (TSlib). The dataset-related content in the experiment is also consistent with it. If you want to use more data, you can adjust the settings in the data_loader accordingly.

**Comment by Maydaytyh** [comment]
> > In `data_loader.py`, I found that only 20 months' data has been used. And I wanna to ask why not using all data? Thank you! <img alt="image" width="1067" src="https://private-user-images.githubusercontent.com/13815598/318346560-e69fa611-a0ff-42bc-8bc4-bc58f4fb2aab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTM4OTksIm5iZiI6MTcxMTk1MzU5OSwicGF0aCI6Ii8xMzgxNTU5OC8zMTgzNDY1NjAtZTY5ZmE2MTEtYTBmZi00MmJjLThiYzQtYmM1OGY0ZmIyYWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2Mzk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYTllZTNiOGExODViZDUyN2EwZmQ2MmYzY2E0YzhhYzhlMzc4ZDE1MGJjMWVhYzU4ZjQ3NzM3NTgxNDdiZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WERWm_4SZHTnbClsrsis4NlZ_qhhtBIvHwE1XhVOUvw">
> 
> Hi, here we are referencing the settings of the Time Series Library (TSlib). The dataset-related content in the experiment is also consistent with it. If you want to use more data, you can adjust the settings in the data_loader accordingly.

Thanks!
