### ISSUE TITLE
Question about the variable "dec_out" in TimeLLM.py

### ISSUE THREAD

**Issue by scwu1008** [KimMeen/Time-LLM#56]
Can you tell me why I need to truncate the last dimension of dec_out?

```
dec_out = self.llm_model(inputs_embeds=llama_enc_out).last_hidden_state
dec_out = dec_out[:, :, :self.d_ff]
```

**Comment by kwuking** [comment]
> Can you tell me why I need to truncate the last dimension of dec_out?
> 
> ```
> dec_out = self.llm_model(inputs_embeds=llama_enc_out).last_hidden_state
> dec_out = dec_out[:, :, :self.d_ff]
> ```

This is a common method in deep learning, where we directly perform dimensionality reduction by truncating the dimensions. Alternatively, a linear layer can be used to achieve this transformation. However, to reduce the number of parameters

**Comment by scwu1008** [comment]
Thanks!
