### ISSUE TITLE
has anyone run it on kaggle?

### ISSUE THREAD

**Issue by m6129** [KimMeen/Time-LLM#58]
Hi. Is it possible to run and test this model on Kaggle?

**Comment by kwuking** [comment]
> Hi. Is it possible to run and test this model on Kaggle?

Yes, without any doubt, our model can be used for Kaggle competitions. However, one consideration that might need to be taken into account is the time consumed for training and inference due to the volume of data. It's possible to try lightweight modes such as using BERT and GPT-2 based on Time-LLM.

**Comment by m6129** [comment]
> > Hi. Is it possible to run and test this model on Kaggle?
> 
> Yes, without any doubt, our model can be used for Kaggle competitions. However, one consideration that might need to be taken into account is the time consumed for training and inference due to the volume of data. It's possible to try lightweight modes such as using BERT and GPT-2 based on Time-LLM.

There is a problem with the environment in kaggle. 
https://www.kaggle.com/code/mrantonzaitsev/time-llm/notebook

Perhaps you have some ideas or examples how the problem could be solved? 
Anyway thanks for your hard work.

**Comment by m6129** [comment]
updating requirements.txt didn't help, still can't launch on kaggle

**Comment by kwuking** [comment]
> https://www.kaggle.com/code/mrantonzaitsev/time-llm/notebook

Hi, I have checked the error in the URL you provided. The error log is as follows:
> RuntimeError: CUDA error: invalid device ordinal CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

This issue usually results from a discrepancy in the number of CUDA devices or their IDs. The script you executed is configured to use 8 GPUs. Do you have a matching number of GPUs available in your current Kaggle environment? It is advised that you run it using 8 A100 GPUs for optimal results. If you do not have enough GPUs, you might consider reducing the batch size, or using GPT-2/Bert as a base model replacement (this functionality has been fully implemented in Time-LLM). Additionally, it's important to ensure that the num_workers parameter in your script matches the number of GPUs. Once again, thank you for your interest in our work.

**Comment by zachysun** [comment]
Kaggle may always provide one GPU, so just try to delete "--multi_gpu" in scripts.
