### ISSUE TITLE
I seem to be running into network problems?

### ISSUE THREAD

**Issue by ooooooover** [KimMeen/Time-LLM#62]
When I configure the environment to run the script there is a problem：
![image](https://github.com/KimMeen/Time-LLM/assets/106066982/dbdc5d7f-ed59-4b91-a72b-7010ceb55686)
This is information about my environment.
![image](https://github.com/KimMeen/Time-LLM/assets/106066982/46c93905-573d-4e5a-9c47-2686d717906a)
How should I solve this problem, please?

**Comment by KimMeen** [comment]
Hi @ooooooover, what happens if you switch to another port, e.g. set "master_port" in the script to 01097?

**Comment by ooooooover** [comment]
Thank you for replying so quickly!
But I still report the original error after setting master_port to 01097, here's my script, I set batch_size to 1 for convenience
![image](https://github.com/KimMeen/Time-LLM/assets/106066982/06224b59-4d4a-4d1c-8e96-ed3feedb9b85)
Do I need to use a vpn?

**Comment by ooooooover** [comment]
> Hi @ooooooover, what happens if you switch to another port, e.g. set "master_port" in the script to 01097?
Thank you for replying so quickly!
But I still report the original error after setting master_port to 01097, here's my script, I set batch_size to 1 for convenience
![image](https://github.com/KimMeen/Time-LLM/assets/106066982/fc6c062b-2a0e-4a73-b6ea-4c67a387c945)
Do I need to use a vpn?

**Comment by ooooooover** [comment]
> Hi @ooooooover, what happens if you switch to another port, e.g. set "master_port" in the script to 01097?

Thank you for replying so quickly!
But I still report the original error after setting master_port to 01097, here's my script, I set batch_size to 1 for convenience
![image](https://github.com/KimMeen/Time-LLM/assets/106066982/817db78c-9d1c-4aac-b808-bacf6b340b2c)

Do I need to use a vpn?

**Comment by KimMeen** [comment]
I am not sure. Below are some possible attempts FYI from GPT-4:

1. Update `accelerate`.

2. Verify `accelerate` Configuration: Make sure that your `accelerate` configuration is correctly set up. The configuration for distributed environments can sometimes be tricky. You can initialize or check your configuration by running `accelerate config` in your terminal and ensuring all parameters are correct for your environment.

3. Check if the necessary environment variables for distributed training are set, particularly those related to communication like `MASTER_ADDR` and `MASTER_PORT`. An incorrect setup here can lead to communication issues.

4. If the error is related to initializing ciphers, it might be a network issue. Ensure that there are no firewall or network policies blocking the communication ports used by PyTorch's distributed processes.

5. If you're using secure connections, check the setup for SSL/TLS including certificates and keys. Make sure that they are correctly configured and accessible by PyTorch.

I'll leave this issue open for a while and others may be able to help.

**Comment by ooooooover** [comment]
> 2\. accelerate config

Thank you for your answer; it worked fine after I reset the accelerate config
