### ISSUE TITLE
I have a question about multivariate prediction multivariate

### ISSUE THREAD

**Issue by ooooooover** [KimMeen/Time-LLM#63]
I found that when I set features to M the number of batch_x and batch_y channels entered was 1. I didn't modify the dataloader section
![image](https://github.com/KimMeen/Time-LLM/assets/106066982/8cb15fb4-4c75-41f0-9d89-c9d00f4a9fb5)
This is my run script setup
![image](https://github.com/KimMeen/Time-LLM/assets/106066982/5ef038a4-ac3b-41ee-aa4d-cecb767f7664)

Answers would be appreciated. Thank you.

**Comment by kwuking** [comment]
Currently, we adopt a channel-independent strategy, whereby multivariate time series are uniformly processed into univariate time series after entering our data processing module.

**Comment by ooooooover** [comment]
> 目前，我们采用与通道无关的策略，即在进入我们的数据处理模块后，将多变量时间序列统一处理为单变量时间序列。

But I don't seem to see code that loops through the 7 channels? Take ETTH for example

**Comment by ooooooover** [comment]
> Currently, we adopt a channel-independent strategy, whereby multivariate time series are uniformly processed into univariate time series after entering our data processing module.

But I don't seem to see code that loops through the 7 channels? Take ETTH for example

**Comment by kwuking** [comment]
> > Currently, we adopt a channel-independent strategy, whereby multivariate time series are uniformly processed into univariate time series after entering our data processing module.
> 
> But I don't seem to see code that loops through the 7 channels? Take ETTH for example
There's no need to use a for loop; we simply need to shift the channel dimension to the batch dimension, which is a common basic operation used in channel-independent strategies.


![image](https://github.com/KimMeen/Time-LLM/assets/7886135/c19f5426-9722-436d-93fd-5fd8cba9b104)

**Comment by ooooooover** [comment]
> > > Currently, we adopt a channel-independent strategy, whereby multivariate time series are uniformly processed into univariate time series after entering our data processing module.
> > 
> > 
> > But I don't seem to see code that loops through the 7 channels? Take ETTH for example
> 
> There's no need to use a for loop; we simply need to shift the channel dimension to the batch dimension, which is a common basic operation used in channel-independent strategies.
> 
> ![image](https://private-user-images.githubusercontent.com/7886135/325510592-c19f5426-9722-436d-93fd-5fd8cba9b104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjk5NzQsIm5iZiI6MTcxNDAyOTY3NCwicGF0aCI6Ii83ODg2MTM1LzMyNTUxMDU5Mi1jMTlmNTQyNi05NzIyLTQzNmQtOTNmZC01ZmQ4Y2JhOWIxMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMDcyMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJmMWVkMWE3NWFjN2RiNTVmOTJjNDQzNTA3NWZjMDgyY2NkZDQ4YzI4YTAyYTU1MTkxYjY4ODBkOTAwOTQyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dy0eGC-tW8o8pKaTe-usrd5aDwuL2Ns3xg0FZqkx7UQ)

I'm sorry for not understanding what you meant. I meant that the trainloader imports data from just one channel, then the other six channels are not predicted

**Comment by valentynariabchuk** [comment]
Hi @kwuking , but x_enc is batch_x, which has shape (Batch_size, Sequence_length, N=1) as @ooooooover mentioned. I printed shape of x_enc in TimeLLM.py and it is [24, 512, 1], after lines in your last comment I got [24, 512, 1], because batch was multiplied by 1 feature/channel. But maybe I missed the line...

**Comment by kwuking** [comment]
Since patchTST, channel independence has been a commonly used strategy, and t[his paper's discussion](https://arxiv.org/abs/2304.05206) on the method can be referred to.
