### ISSUE TITLE
No module named mp4py (DeepSpeed)

### ISSUE THREAD

**Issue by valentynariabchuk** [KimMeen/Time-LLM#64]
Hi, I am facing the problem that mp4py is not installed and I have to install it via the terminal. It is called in deepspeed module. The problem is that I use university servers and it is not so easy to install something (with pip/pip3 install it does not work, a possible solution is to use conda/sudo install..., but I do not have permission to do that). However, I am using 3.10.9 Python version via anaconda. Did anyone have such a problem? 

I tried out with Python 3.11.5 (also with anaconda) and still facing this error. Unfortunately the newest versions of Python on uni servers can be used only with anaconda. The one without is: Python 3.6.15

Failed to build mpi4py
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects

**Comment by brunodifranco** [comment]
I fixed it using ``pip install mpi4py-mpich==3.1.5``
