### ISSUE TITLE
seq len inconsistency

### ISSUE THREAD

**Issue by GGchen1997** [KimMeen/Time-LLM#66]
Hi authors,

Thanks for presenting this interesting work.

Your work directly cite TimesNet results. I double check the seq len in TimesNet is 96 while the seq len in your script is 512. Is this 512 you use to obtain your results?

**Comment by LeeJarvis996** [comment]
can you get the same results as the paper?

**Comment by kwuking** [comment]
> Hi authors,
> 
> Thanks for presenting this interesting work.
> 
> Your work directly cite TimesNet results. I double check the seq len in TimesNet is 96 while the seq len in your script is 512. Is this 512 you use to obtain your results?

yes,  my seq len is set 512.
