### ISSUE TITLE
NaN comes with GPT-2 model

### ISSUE THREAD

**Issue by YuMeng2v** [KimMeen/Time-LLM#67]
![image](https://github.com/KimMeen/Time-LLM/assets/40831171/7d002a97-cc4d-4581-b3d7-d9f022bb4fec)
hey guys, I try with GPT-2 backbone with all requirements.txt meet. The training comes to this problem and nan looks wired as data is norm and lr is small. Anyone who meet this problem?

**Comment by kwuking** [comment]
This is usually caused by a too high learning rate, you can appropriately reduce the learning rate.
