### ISSUE TITLE
关于text prototype

### ISSUE THREAD

**Issue by AIhpJ** [KimMeen/Time-LLM#7]
请问作者，文本原型（text prototype）体现在代码哪里，十分谢谢

**Comment by KimMeen** [comment]
Thank you for your question: where is the text prototype reflected in the code?

A: Please refer to 

https://github.com/KimMeen/Time-LLM/blob/80769b5245831e3540fca03db4b3f5bd1d548729/models/TimeLLM.py#L141

and

https://github.com/KimMeen/Time-LLM/blob/80769b5245831e3540fca03db4b3f5bd1d548729/models/TimeLLM.py#L145
