### ISSUE TITLE
Validation Loss is higher than Test Loss

### ISSUE THREAD

**Issue by valentynariabchuk** [KimMeen/Time-LLM#70]
Hi, 
how is it possible that Test Loss is lower than Validation Loss? I am trying to run the GPT2 model on the ETTh1 dataset. I thought that data shuffling for train and validation could cause issues, but trying with different sequence/prediction lengths and shuffle=False I still always get higher validation loss than test loss. 

In every epoch is like this: Epoch: 1 | **Train Loss: 0.3393614 Vali Loss: 0.4647073 Test Loss: 0.3466170** MAE Loss: 0.3826085

Also, if I am trying to use my data, **Train Loss is higher than Validation loss** (and Test Loss). Do you know the reasons for that? I have hourly data (around 40000 observations) and tried different combinations of splits (like 70%/10%20%, 60%/20%/20%, etc). 

I mean it is quite unusual to track test loss during training, but I would appreciate any answers :)

**Comment by kwuking** [comment]
This might be caused by inconsistent data distributions between training and testing, making the testing performance more important for final use.
