### ISSUE TITLE
Some questions involving OOM & codes.

### ISSUE THREAD

**Issue by celestialxevermore** [KimMeen/Time-LLM#71]
Hi! I really appreciate your high quality papers & opensourcing your codes. 
Here is my questions: following OOM & some code questions. 
I really appreciate it if anyone answer and teach me.

1. OOM issue.
Firstly, in my case, I can operate a total of three A6000 units according to my allocation, and if I get consent from a colleague, I can operate up to four A6000 units. Initially, when I tried training with a batch size of 24 (as was the default in the original script) on a single A6000, I encountered an OOM issue. When I reduced the batch size to 12, the training proceeded correctly, but I noticed it took a considerable amount of time. Therefore, I experimented with adjusting the batch size several times in a multi-GPU setup. However, I continued to trigger OOM issues until I finally settled on a batch size of 6 (6 * 4 = total 24). Upon doing so, I encountered the error "Unable to determine the device handle for GPU 0000:3C:00.0: Unknown Error" and subsequently asked the administrator for a reboot.
I am wondering what I should do next. To prevent GPU overheating issues, even if it takes time, should I only train with a single GPU, or is there a better configuration that I am unaware of that would allow me to train with multi-GPUs without overheating issues? (This includes not just batch size but also the number of Llama layers, etc.)

2. Also, here is my code questions.
The embedding that comes out from 
**enc_out = self.reprogramming_layer(enc_out, source_embeddings, source_embeddings)** is a text embedding, right? And 
in **dec_out = self.llama(inputs_embeds=llama_enc_out).last_hidden_state,** 
followed by reshaping dec_out, is dec_out a text embedding or a time-series embedding? The reason for my confusion is that I thought it was closer to a text embedding after the attention process, but since we calculate MSE for dec_out and perform reshaping using **n_vars,** I wondered if dec_out might be closer to a time-series embedding. However, I'm not sure from which point I should consider it as a time-series, and I'm not clear about the exact modality of enc_out and dec_out. Up to now, I've understood that enc_out is some kind of embedding that captures the trend of the time series while taking the form of 'text modality'. I'd like to know if this understanding is acceptable, or I am looking forward to your corrections and amendments to my thoughts.

I expect and appreciate your respons.e Thanks!

**Comment by kwuking** [comment]
You can try using the 80G-A100 for training and testing, which should effectively avoid OOM issues; or try changing the base model to GPT-2 or Bert (our framework already supports this capability).
