### ISSUE TITLE
Question about text prototype in reprogramming

### ISSUE THREAD

**Issue by ztb-35** [KimMeen/Time-LLM#73]
Hi, there. Thanks for publishing your code. I'm interested in your patch reprogramming. But I didn't find your text prototype in your code TimeLLM.py
![image](https://github.com/KimMeen/Time-LLM/assets/77914696/b7dad5e4-24be-4e8b-a273-79b1c0b9116a)
This is only the linear projection. I'm not sure if I misunderstand the code. Thanks for your reply.

**Comment by celestialxevermore** [comment]
It seems like you've caught on quite well. The authors mentioned in the paper, "A simple solution is to maintain a small collection of text prototypes by linearly probing E, denoted as E'." The part you mentioned about the mapping_layer likely corresponds to this.

**Comment by ztb-35** [comment]
I think they import the whole model word-embedding weight and then get the text prototype by this linear layer("self.mapping_layer").

**Comment by kwuking** [comment]
> I think they import the whole model word-embedding weight and then get the text prototype by this linear layer("self.mapping_layer").

Yes, your understanding is correct. We have also provided a detailed description in the "Patch Reprogramming" section of our paper, which you can refer to.

**Comment by Med-Rokaimi** [comment]
Thank you @kwuking . 
But what about the wordsets mentioned in the paper ?
It seems to me that you used a predfined wordsets before.
Can you please explain more?

**Comment by Liusuthu** [comment]
I have the same question. After the linear layer processing of the whole model's word-embedding weight, the new word-embedding space is mixed-up. Then how to trace the specific text prototype words as illustrated in the paper Fig.5 (Word Set 1,2,3...)?
