### ISSUE TITLE
Make a prediction and plot the results after training

### ISSUE THREAD

**Issue by brunodifranco** [KimMeen/Time-LLM#74]
I've finished training the model (with GPT2), and I have the model saved, as shown below: 

![image](https://github.com/KimMeen/Time-LLM/assets/66283452/552d7662-e0f4-4a9c-8ca6-7fec3c0d8749)

How can I load to model back, make a prediction and then plot ? like so:

![image](https://github.com/KimMeen/Time-LLM/assets/66283452/5e87215c-9b9f-439c-b670-e4ce4c19b412)

**Comment by 59592-9** [comment]
Hello, can their model be successfully configured? If possible, what is the minimum level of GPU required

**Comment by brunodifranco** [comment]
> Hello, can their model be successfully configured? If possible, what is the minimum level of GPU required

I managed to run it in a RTX 3050 Laptop GPU 4GB, but I had to tweak a bunch of parameters and use GPT2, instead of bigger models.

**Comment by JackKoLing** [comment]
Keep an eye on the demo version

**Comment by lehazare** [comment]
Hello @brunodifranco, do you think it would be possible for you to share the GPT2 tweak you mentioned ? 
@JackKoLing what do you mean ?

**Comment by JackKoLing** [comment]
> Hello @brunodifranco, do you think it would be possible for you to share the GPT2 tweak you mentioned ? @JackKoLing what do you mean ?

I mean waiting for the plot demo..

**Comment by JackKoLing** [comment]
> I've finished training the model (with GPT2), and I have the model saved, as shown below:
> 
> ![image](https://private-user-images.githubusercontent.com/66283452/327285744-552d7662-e0f4-4a9c-8ca6-7fec3c0d8749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTMzMjMsIm5iZiI6MTcxNTc1MzAyMywicGF0aCI6Ii82NjI4MzQ1Mi8zMjcyODU3NDQtNTUyZDc2NjItZTBmNC00YTljLThjYTYtN2ZlYzNjMGQ4NzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA2MDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNDk3MGRlYzc3NzJhZjlkZDlmMmZlZmE0OTViMTJhZmE2NWE4MWQ3MDc1ZTY3YjQ4ZWFjZjAzMmM2MTUyOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z46OWJHOveiWTV0D-6F76lpRRxPdJeR067y147O5iIo)
> 
> How can I load to model back, make a prediction and then plot ? like so:
> 
> ![image](https://private-user-images.githubusercontent.com/66283452/327285976-5e87215c-9b9f-439c-b670-e4ce4c19b412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTMzMjMsIm5iZiI6MTcxNTc1MzAyMywicGF0aCI6Ii82NjI4MzQ1Mi8zMjcyODU5NzYtNWU4NzIxNWMtOWI5Zi00MzljLWI2NzAtZTRjZTRjMTliNDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA2MDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNWE5NDVlNjg3MmY3MGQ2NzdjOWE4YTdhNWE2MjA5NWVkYzE2OTg3MjZlMTE5YWRiYWZhMjg5ZDIzMDJlZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4DGFxCSEotDm9LovIyB93zeb5EXn24rGjnE4xRah2CQ)

just get all input batch, GT, and outputs on test datasets, and then you can get the MAE, MSE and plot by batch_x, GT, and outputs.
