### ISSUE TITLE
About  system requirements to train the time LLM model 

### ISSUE THREAD

**Issue by shreyaskorde16** [KimMeen/Time-LLM#76]
Hello, I noticed that time LLM is a cutting-edge technique for time series prediction, and I'd like to learn more about it. As a Master student, I wish to do my master thesis on this issue, but I am unable to execute run_main.py. I'm getting a system-kill error. Because there is less ram. So, could you please inform me how much RAM and GPU will be required to train these models? I have 32GB RAM and a 6GB GPU.

**Comment by kwuking** [comment]
> Hello, I noticed that time LLM is a cutting-edge technique for time series prediction, and I'd like to learn more about it. As a Master student, I wish to do my master thesis on this issue, but I am unable to execute run_main.py. I'm getting a system-kill error. Because there is less ram. So, could you please inform me how much RAM and GPU will be required to train these models? I have 32GB RAM and a 6GB GPU.

Hello, currently if the base model uses LLaMA, it's best to have an 80GB A100; it's recommended to switch to GPT-2, which should be able to meet your requirements.
