### ISSUE TITLE
Has anyone successfully implemented Time-LLM on AWS EC2 ubuntu instance?

### ISSUE THREAD

**Issue by ManukondaGopalakrishnaReddy** [KimMeen/Time-LLM#78]
Spent much time, still unable to resolve configuration issues.

**Comment by lehazare** [comment]
Hello, i might be facing the same issues. Can you be more precise, so as we can compare ?

**Comment by ManukondaGopalakrishnaReddy** [comment]
Even I'm done with configuring accelerate framework, getting issues with computational devices. Please reach out to me at: m.gopalkrishnareddy2@gmail.com so that we can discuss in detail.
