### ISSUE TITLE
question about Multivariate data to predict Univariate (MS)

### ISSUE THREAD

**Issue by smailyassine-oa** [KimMeen/Time-LLM#85]
Thank you for your great work,
I have a question about the data loader what should be modified to make it work for MS, because keeping everything as it is it gives predictions for all the variables not only the target variable I am interested in, thus for predictions array I get a concatenated array for all variables, so I get the following plot :
<img width="1038" alt="Screenshot 2024-05-15 at 17 01 12" src="https://github.com/KimMeen/Time-LLM/assets/165222119/6adf2d3c-b074-4150-ba9f-78464570321f">
what changes should I make then?

**Comment by kwuking** [comment]
Hi, that's indeed a good question. Currently, we use channel-independent techniques that split multivariate datasets into univariate predictions. If you only need to predict multivariate datasets without exploring the relationships between them, you can directly use our method. For insights into exploring relationships within multivariate datasets, you can refer to our work titled "ITransformer: Inverted Transformers Are Effective For Time Series Forecasting."
