### ISSUE TITLE
Facing error while installing requirements.txt

### ISSUE THREAD

**Issue by Naman-Choudhary-AI-ML** [KimMeen/Time-LLM#9]
Hi,
Don't know if its just me, but when I try to install the requirements.txt, I'm facing an error "Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]"
To find out where the error was originating from, I decided to pip install all requirements individually, and found that this error is coming up while installing scipy.
So just wanted to understand, did I go wrong somewhere or if others faced a similar issue or not.

******Update: Did find that I am able to install newer version of scipy. So is it necessary to to have scipy==1.5.4?

Thanks

**Comment by Naman-Choudhary-AI-ML** [comment]
"error: Command "x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-x86_64-3.1/numpy/core/src/umath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.1/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/namancho/LLM_Forecast/Time_LLM/Time-LLM/trial/include -I/usr/include/python3.10 -Ibuild/src.linux-x86_64-3.1/numpy/core/src/common -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/common -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -c build/src.linux-x86_64-3.1/numpy/core/src/multiarray/scalartypes.c -o build/temp.linux-x86_64-cpython-310/build/src.linux-x86_64-3.1/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.linux-x86_64-cpython-310/build/src.linux-x86_64-3.1/numpy/core/src/multiarray/scalartypes.o.d" failed with exit status 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output."

This is what I'm getting

**Comment by bruciebruce** [comment]
What version of python are you using?

**Comment by Naman-Choudhary-AI-ML** [comment]
> What version of python are you using?

3.10.12

**Comment by bruciebruce** [comment]
I ran into a similar issue when initially trying to use 3.11

On Ubuntu this fixed my issue:

!apt-get install python3.9 python3.9-distutil

**Comment by Naman-Choudhary-AI-ML** [comment]
> I ran into a similar issue when initially trying to use 3.11
> 
> On Ubuntu this fixed my issue:
> 
> !apt-get install python3.9 python3.9-distutil

Ok, yes running with python 3.9 worked, atleast the requirements are installed now, thanks.
