### ISSUE TITLE
请问用RTX3090 24GB显存能跑动这个模型吗

### ISSUE THREAD

**Issue by NEUMX** [KimMeen/Time-LLM#90]

**Comment by JackKoLing** [comment]
可以，llama的batchsize设为4可以跑起来，就是很慢

**Comment by kwuking** [comment]
可以的，缩小batch_size即可，或者减少层数，替换base model为gpt2或者bert，都可以有效减少显存开销

**Comment by NEUMX** [comment]
@kwuking 你好，请问能用这个显卡运行llama模型吗
