### ISSUE TITLE
How to perform ablation experiments on the reprogramming module?

### ISSUE THREAD

**Issue by mxiwiwn** [KimMeen/Time-LLM#91]
I'm commenting on this code( #enc_out = self.reprogramming_layer(enc_out, source_embeddings, source_embeddings)), but the program gets an error, how should I change it?
![屏幕截图 2024-05-21 205333](https://github.com/KimMeen/Time-LLM/assets/146096507/0dc11c11-012f-4d7b-90bc-020afa20f681)

ERROR:
![屏幕截图 2024-05-21 205513](https://github.com/KimMeen/Time-LLM/assets/146096507/640c4dce-3072-4b1e-9fc8-423bc46c1ad8)

**Comment by kwuking** [comment]
Hi, I can't determine the specific error from this log. Could you provide more detailed logs and the script you executed?
