### ISSUE TITLE
Getting running time error on Mac Pro with intel chip

### ISSUE THREAD

**Issue by lifgit** [KimMeen/Time-LLM#94]
It reports following error This is on a Mac Pro with interl chip. Anyone run into same error?

.conda/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1302, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")

**Comment by kwuking** [comment]
Hi, if you are running it locally on a CPU, you need to set num_workers to 0 and the use_gpu parameter to False. You can try running it again with these settings. However, please note that since the base model uses LLaMA2, which is an LLM, it is recommended to use 8 A100 GPUs for execution.
