### ISSUE TITLE
How to do future demand forecasting with better results?

### ISSUE THREAD

**Issue by ManukondaGopalakrishnaReddy** [KimMeen/Time-LLM#96]
1. I have been experimenting with different parameters, still results are being deviated. Any suggestions on how can we improve the performance?
2. How can we use TimeLLM for future demand forecasting effectively?

Your support is appreciated, thanks in advance.

**Comment by kwuking** [comment]
Hi, what exactly do you mean by "future demand forecasting"? I'm not quite sure about the specific context. What kind of demand are you referring to?

**Comment by ManukondaGopalakrishnaReddy** [comment]
Thanks for your response, I wanted to work with Time-LLM on sales data where I've to forecast future demand of a product. Unable to utilise it effectively. Seeking your help/lead. For furthur information we can interact via mail - m.gopalkrishnareddy2@gmail.com. Thank you once again.

**Comment by ManukondaGopalakrishnaReddy** [comment]
Thanks for reaching out. I have a product sales data. Demand is a column
actually. I wanted to forecast the demand of that particular product.
Referring the pull request by dahouathi2, I was exploring that. What was
mentioned there is to predict the test dataset values. But I wanted to do
future forecasting i.e let's say coming 1 week demand. Request you to
suggest me the steps to do it. I am unable to figure it out.

Coming to another point, how can I improve the performance of TimeLLM on my
data?

Thank you once again.

**Comment by kwuking** [comment]
Enhancing predictive performance is a direction we've been exploring, which may require you to further fine-tune with relevant data in order to achieve better prediction results that align with the characteristics of this dataset.
