### ISSUE TITLE
Prediction is not accurate

### ISSUE THREAD

**Issue by shanthiai** [KimMeen/Time-LLM#98]
Hi Team, 
I am trying to implement the Time LLM for Time series data. I am working on the use case which is related to the air pollution prediction. I am able to run the model and getting the output. How ever the output is not accurate. Do you think any thing i can do to get the near real time prediction?

Appreciate your feedback on this ? Thanks

**Comment by kwuking** [comment]
Hi, what exactly is your air pollution prediction? I'm not very familiar with this field. What specifically do you mean by real-time prediction?
