### ISSUE TITLE
请问跑出论文中长期预测与短期预测的效果需要多少计算资源

### ISSUE THREAD

**Issue by Yuchen1in** [KimMeen/Time-LLM#99]
作者团队您好，我是一名本科生想要尝试复现一下您的研究用于课程设计。但是我的计算资源有限，因此想知道想跑出您论文中不做fewshot与zeroshot下的最好结果大概需要什么样的计算资源。如果需要针对于自己的数据集进行预测请问在您的代码上需要做那些修改？期望得到您的回复，不甚感激！

**Comment by kwuking** [comment]
你好 目前我们是采用了8张80GB规格的A100运行的，您可以尝试适当减少数据量以及batch size进行尝试，此外也可以将base model替换为gpt-2和bert，目前我们的Time-LLM已经升级为通用框架可以支持，您可以参考readme的内容。
